{   'AreaNeighborhood': '',
    'AssessorMarket': '',
    'AssociatedParcels': [],
    'DeedTransitionUrl': '',
    'ElementarySchoolDistrict': '',
    'Geo': {   'address': '',
               'lat': 0,
               'long': 0},
    'HighSchoolDistrict': '',
    'Improvements': [],
    'IsCancelled': False,
    'IsCommercial': False,
    'IsRental': False,
    'IsResidential': False,
    'LocalJusidiction': '',
    'Lot': '',
    'LotSize': '',
    'MCR': '',
    'MapIDs': {   'Book/Map Maps': [   {   'FileName': '',
                                           'UpdateDate': '',
                                           'Url': ''},
                                       {   'FileName': '',
                                           'UpdateDate': '',
                                           'Url': ''},
                                       {   'FileName': '',
                                           'UpdateDate': '',
                                           'Url': ''},
                                       {   'FileName': '',
                                           'UpdateDate': '',
                                           'Url': ''},
                                       {   'FileName': '',
                                           'UpdateDate': '',
                                           'Url': ''},
                                       {   'FileName': '',
                                           'UpdateDate': '',
                                           'Url': ''},
                                       {   'FileName': '',
                                           'UpdateDate': '',
                                           'Url': ''},
                                       {   'FileName': '',
                                           'UpdateDate': '',
                                           'Url': ''},
                                       {   'FileName': '',
                                           'UpdateDate': '',
                                           'Url': ''},
                                       {   'FileName': '',
                                           'UpdateDate': '',
                                           'Url': ''},
                                       {   'FileName': '',
                                           'UpdateDate': '',
                                           'Url': ''},
                                       {   'FileName': '',
                                           'UpdateDate': '',
                                           'Url': ''}],
                  'MCR Maps': [   {   'FileName': '',
                                      'UpdateDate': '',
                                      'Url': ''},
                                  {   'FileName': '',
                                      'UpdateDate': '',
                                      'Url': ''},
                                  {   'FileName': '',
                                      'UpdateDate': '',
                                      'Url': ''},
                                  {   'FileName': '',
                                      'UpdateDate': '',
                                      'Url': ''},
                                  {   'FileName': '',
                                      'UpdateDate': '',
                                      'Url': ''}],
                  'Parcel Maps': [   {   'FileName': '',
                                         'UpdateDate': '',
                                         'Url': ''}],
                  'S/T/R Maps': [],
                  'Subdivision Maps': [   {   'FileName': '',
                                              'UpdateDate': '',
                                              'Url': ''},
                                          {   'FileName': '',
                                              'UpdateDate': '',
                                              'Url': ''},
                                          {   'FileName': '',
                                              'UpdateDate': '',
                                              'Url': ''},
                                          {   'FileName': '',
                                              'UpdateDate': '',
                                              'Url': ''},
                                          {   'FileName': '',
                                              'UpdateDate': '',
                                              'Url': ''}]},
    'MapidExists': False,
    'McrTransitionUrl': '',
    'MoreAssociatedParcelsExist': False,
    'NumberOfParcelsInMCR': 0,
    'NumberOfParcelsInSTR': 0,
    'NumberOfParcelsInSubdivision': 0,
    'Owner': {   'ContoOwnership': None,
                 'DeedDate': '',
                 'DeedType': '',
                 'DeedTypeID': None,
                 'FullMailingAddress': '',
                 'InCareOf': None,
                 'MailingAddress1': '',
                 'MailingAddress2': None,
                 'MailingCity': '',
                 'MailingCountry': None,
                 'MailingState': '',
                 'MailingZip': '',
                 'MostCurrentDeed': '',
                 'OwnerID': '',
                 'Ownership': '',
                 'Redacted': False,
                 'SaleDate': '',
                 'SalePrice': ''},
    'PEPropUseDesc': '',
    'ParcelStatus': None,
    'PropertyAddress': '',
    'PropertyDescription': '',
    'PropertyType': '',
    'PropertyUseCode': '',
    'ResidentialPropertyData': {   'AreaNeighborhood': '',
                                   'AssessorMarket': '',
                                   'BathFixtures': '',
                                   'ConstructionYear': '',
                                   'Cooling': '',
                                   'CoveredParking': False,
                                   'Detached_Livable_sqft': None,
                                   'ExteriorWalls': '',
                                   'Heating': '',
                                   'ImprovementQualityGrade': '',
                                   'LivableSpace': '',
                                   'LocationalCharacteristics': '',
                                   'LocationalFactors': '',
                                   'LotSize': '',
                                   'NumberOfCarports': None,
                                   'NumberOfCoveredPatios': '',
                                   'NumberOfGarages': '',
                                   'NumberOfPatios': '',
                                   'NumberOfUncoveredPatios': '',
                                   'OriginalConstructionYear': '',
                                   'OtherStructures': None,
                                   'PEImprovementQualityGrade': '',
                                   'ParkingDetails': {   'ParkingCount': '',
                                                         'ParkingType': ''},
                                   'ParkingType': '',
                                   'PatioType': '',
                                   'PhysicalCondition': None,
                                   'Pool': False,
                                   'RoofType': ''},
    'SectionTownshipRange': '',
    'SimilarParcels': [   {   'ConstructionYear': '',
                              'ForeClosed': '',
                              'FullCashValue': '',
                              'LandSize': '',
                              'LivableSqFootage': '',
                              'Parcel': '',
                              'PoolArea': [],
                              'SalesPriceDate': '',
                              'SitusAddress': ''},
                          {   'ConstructionYear': '',
                              'ForeClosed': '',
                              'FullCashValue': '',
                              'LandSize': '',
                              'LivableSqFootage': '',
                              'Parcel': '',
                              'PoolArea': [],
                              'SalesPriceDate': '',
                              'SitusAddress': ''},
                          {   'ConstructionYear': '',
                              'ForeClosed': '',
                              'FullCashValue': '',
                              'LandSize': '',
                              'LivableSqFootage': '',
                              'Parcel': '',
                              'PoolArea': [],
                              'SalesPriceDate': '',
                              'SitusAddress': ''},
                          {   'ConstructionYear': '',
                              'ForeClosed': '',
                              'FullCashValue': '',
                              'LandSize': '',
                              'LivableSqFootage': '',
                              'Parcel': '',
                              'PoolArea': [],
                              'SalesPriceDate': '',
                              'SitusAddress': ''},
                          {   'ConstructionYear': '',
                              'ForeClosed': '',
                              'FullCashValue': '',
                              'LandSize': '',
                              'LivableSqFootage': '',
                              'Parcel': '',
                              'PoolArea': [],
                              'SalesPriceDate': '',
                              'SitusAddress': ''}],
    'Sketches': {   'Pages': [   {   'APN': '',
                                     'PageNum': 0,
                                     'Sketch': ''},
                                 {   'APN': '',
                                     'PageNum': 0,
                                     'Sketch': ''}],
                    'TotalPages': 0},
    'SubdivisionName': '',
    'TaxAreaCode': '',
    'TreasurersTransitionUrl': '',
    'Valuations': [   {   'AssessedFCV': '',
                          'AssessedLPV': '',
                          'AssessmentRatioPercentage': '',
                          'FullCashValue': '',
                          'LegalClassification': '',
                          'LegalClassificationCode': '',
                          'LimitedPropertyValue': '',
                          'NoticeOfChangeIndc': '',
                          'PEPropUseDesc': '',
                          'PropertyUseCode': '',
                          'TaxAreaCode': '',
                          'TaxYear': '',
                          'ValuationSource': ''},
                      {   'AssessedFCV': '',
                          'AssessedLPV': '',
                          'AssessmentRatioPercentage': '',
                          'FullCashValue': '',
                          'LegalClassification': '',
                          'LegalClassificationCode': '',
                          'LimitedPropertyValue': '',
                          'NoticeOfChangeIndc': '',
                          'PEPropUseDesc': '',
                          'PropertyUseCode': '',
                          'TaxAreaCode': '',
                          'TaxYear': '',
                          'ValuationSource': ''},
                      {   'AssessedFCV': '',
                          'AssessedLPV': '',
                          'AssessmentRatioPercentage': '',
                          'FullCashValue': '',
                          'LegalClassification': '',
                          'LegalClassificationCode': '',
                          'LimitedPropertyValue': '',
                          'NoticeOfChangeIndc': '',
                          'PEPropUseDesc': '',
                          'PropertyUseCode': '',
                          'TaxAreaCode': '',
                          'TaxYear': '',
                          'ValuationSource': ''},
                      {   'AssessedFCV': '',
                          'AssessedLPV': '',
                          'AssessmentRatioPercentage': '',
                          'FullCashValue': '',
                          'LegalClassification': '',
                          'LegalClassificationCode': '',
                          'LimitedPropertyValue': '',
                          'NoticeOfChangeIndc': '',
                          'PEPropUseDesc': '',
                          'PropertyUseCode': '',
                          'TaxAreaCode': '',
                          'TaxYear': '',
                          'ValuationSource': ''},
                      {   'AssessedFCV': '',
                          'AssessedLPV': '',
                          'AssessmentRatioPercentage': '',
                          'FullCashValue': '',
                          'LegalClassification': '',
                          'LegalClassificationCode': '',
                          'LimitedPropertyValue': '',
                          'NoticeOfChangeIndc': '',
                          'PEPropUseDesc': '',
                          'PropertyUseCode': '',
                          'TaxAreaCode': '',
                          'TaxYear': '',
                          'ValuationSource': ''},
                      {   'AssessedFCV': '',
                          'AssessedLPV': '',
                          'AssessmentRatioPercentage': '',
                          'FullCashValue': '',
                          'LegalClassification': '',
                          'LegalClassificationCode': '',
                          'LimitedPropertyValue': '',
                          'NoticeOfChangeIndc': '',
                          'PEPropUseDesc': '',
                          'PropertyUseCode': '',
                          'TaxAreaCode': '',
                          'TaxYear': '',
                          'ValuationSource': ''}],
    'Zoning': ''}

[#'MCR', 'AssociatedParcels', 'MoreAssociatedParcelsExist',
       'PropertyAddress', #'PropertyDescription',
       #'LotSize', #'IsResidential', 'MapidExists', 'SectionTownshipRange', 'AssessorMarket',
       #'AreaNeighborhood', 'SubdivisionName', 'Lot', 'HighSchoolDistrict',
       #'ElementarySchoolDistrict', 'LocalJusidiction', 'PropertyType',
       #'ParcelStatus', 'Zoning', 'IsRental', 'McrTransitionUrl',
       #'TreasurersTransitionUrl', 'DeedTransitionUrl', 'IsCommercial',
       #'IsCancelled', 'NumberOfParcelsInSubdivision', 'Improvements',
       #'Valuations', 'TaxAreaCode', 'PropertyUseCode', 'PEPropUseDesc',
       #'NumberOfParcelsInMCR', 'NumberOfParcelsInSTR', 'SimilarParcels',
       #'Owner.OwnerID',
       #'Owner.Ownership', 'Owner.InCareOf',
       #'Owner.ContoOwnership', 'Owner.MailingAddress1',
       #'Owner.MailingAddress2', 'Owner.MailingCity', 'Owner.MailingState',
       #'Owner.MailingZip', 'Owner.MailingCountry', 'Owner.MostCurrentDeed',
       #'Owner.DeedDate', 'Owner.DeedType',
       'Owner.SalePrice', 'Owner.SaleDate',
       #'Owner.Redacted', 'Owner.FullMailingAddress', 'Owner.DeedTypeID',
       #'Geo.lat', 'Geo.long', 'Geo.address',
       'ResidentialPropertyData.ConstructionYear',
       #'ResidentialPropertyData.OriginalConstructionYear',
       'ResidentialPropertyData.LotSize',
       'ResidentialPropertyData.LivableSpace',
       'ResidentialPropertyData.Detached_Livable_sqft',
       #'ResidentialPropertyData.AssessorMarket',
       #'ResidentialPropertyData.AreaNeighborhood',
       'ResidentialPropertyData.Pool',
       #'ResidentialPropertyData.PEImprovementQualityGrade',
       #'ResidentialPropertyData.ImprovementQualityGrade',
       #'ResidentialPropertyData.NumberOfCoveredPatios',
       #'ResidentialPropertyData.NumberOfUncoveredPatios',
       #'ResidentialPropertyData.NumberOfPatios',
       #'ResidentialPropertyData.PatioType',
       #'ResidentialPropertyData.ExteriorWalls',
       #'ResidentialPropertyData.RoofType',
       #'ResidentialPropertyData.BathFixtures',
       #'ResidentialPropertyData.Cooling', 'ResidentialPropertyData.Heating',
       #'ResidentialPropertyData.NumberOfGarages',
       # 'ResidentialPropertyData.NumberOfCarports',
       # 'ResidentialPropertyData.ParkingDetails.ParkingType',
       # 'ResidentialPropertyData.ParkingDetails.ParkingCount',
       # 'ResidentialPropertyData.LocationalFactors',
       # 'ResidentialPropertyData.OtherStructures',
       # 'ResidentialPropertyData.ParkingType',
       # 'ResidentialPropertyData.CoveredParking',
       # 'ResidentialPropertyData.LocationalCharacteristics',
       # 'ResidentialPropertyData.PhysicalCondition', 'Sketches.TotalPages',
       # 'Sketches.Pages', 'MapIDs.Parcel Maps', 'MapIDs.Subdivision Maps',
       # 'MapIDs.MCR Maps', 'MapIDs.S/T/R Maps', 'MapIDs.Book/Map Maps']


FIELDS = ['ResidentialPropertyData.LotSize', 'ResidentialPropertyData.LivableSpace','ResidentialPropertyData.ConstructionYear','ResidentialPropertyData.Pool','PropertyAddress','Owner.SalePrice','Owner.SaleDate']
