[tool.poetry]
name = "mfranceschi-minesweeper"
version = "0.2.3"
description = "A cool minesweeper"
authors = ["mfranceschi"]
license = "MIT"
readme = "Readme.md"
repository = "https://github.com/mfranceschi/Minesweeper/"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Topic :: Games/Entertainment",
    "Topic :: Games/Entertainment :: Arcade",
    "Topic :: Games/Entertainment :: Board Games"
]
include = ["*.txt", "Readme.md"]

[tool.poetry.dependencies]
python = "^3.7"
overrides = "~6.1"
Pillow = "^8.3"

[tool.poetry.dev-dependencies]
pytest = "~6.2"

[tool.poetry.scripts]
mf-mines = "mfranceschi_minesweeper.main:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
