
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-03T10:42:44+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "1cdee4a12cab6ce4408662eba6b5f3436eb87817",
 "version": "0.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
