# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ReportMailerChild(Model):
    """ReportMailerChild.

    :param last_sent: The date that the report mailer was last processed
    :type last_sent: datetime
    :param next_sent: The next time the report mailer will be processed
    :type next_sent: datetime
    :param report_batch:
    :type report_batch: ~energycap.sdk.models.ReportBatchChild
    :param report_emails_sent: Report emails successfully sent to their
     recipient
    :type report_emails_sent: list[~energycap.sdk.models.ReportEmail]
    :param report_emails_not_sent: Report emails not successfully sent to
     their recipients
    :type report_emails_not_sent: list[~energycap.sdk.models.ReportEmail]
    """

    _attribute_map = {
        'last_sent': {'key': 'lastSent', 'type': 'iso-8601'},
        'next_sent': {'key': 'nextSent', 'type': 'iso-8601'},
        'report_batch': {'key': 'reportBatch', 'type': 'ReportBatchChild'},
        'report_emails_sent': {'key': 'reportEmailsSent', 'type': '[ReportEmail]'},
        'report_emails_not_sent': {'key': 'reportEmailsNotSent', 'type': '[ReportEmail]'},
    }

    def __init__(self, **kwargs):
        super(ReportMailerChild, self).__init__(**kwargs)
        self.last_sent = kwargs.get('last_sent', None)
        self.next_sent = kwargs.get('next_sent', None)
        self.report_batch = kwargs.get('report_batch', None)
        self.report_emails_sent = kwargs.get('report_emails_sent', None)
        self.report_emails_not_sent = kwargs.get('report_emails_not_sent', None)
