[tool.poetry]
name = "classification-service"
version = "0.1.0"
description = ""
authors = ["pvasisht <prajwal_prakashvasisht@intuit.com>"]

[tool.poetry.dependencies]
python = "^3.7"
flask = "*"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
