# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"read_csv_from_s3": "01_read_csv_from_s3.ipynb"}

modules = ["read_csv_from_s3.py"]

doc_url = "//vocus_sagemaker_utils/"

git_url = "https://gitlab.vocus.com.au/Analytics/machine-learning-platform//vocus_sagemaker_utils/tree/master/"

def custom_doc_links(name): return None
