[tool.poetry]
name = "qvapay"
version = "0.0.3"
description = "Python SDK for the QvaPay API"
authors = ["Carlos Lugones <contact@lugodev.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
httpx = "0.19.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
