VERSION_YEAR = 2021
VERSION_MONTH = int('09')
VERSION_DAY = int('05')
VERSION_HOUR = int('09')
VERSION_MINUTE = int('40')
MAJOR_VERSION = 0
MINOR_VERSION = 4
PATCH_VERSION = 202109050940
version_date = '2021/09/05 09:40'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
