
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-01T11:28:02+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d72e7eb279dd1dd1e1e19d8873f55317341802bb",
 "version": "0.7.0.post.dev420"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
