[tool.poetry]
name = "annofabapi-3dpc-extensions"
version = "0.1.0"
description = "annofabapiの3DPC Editor用の拡張機能です。"
authors = ["yuji38kwmt"]
packages = [
    { include = "annofab_3dpc" }
]
readme="README.md"
repository="https://github.com/kurusugawa-computer/annofabapi-3dpc-extensions"
classifiers = [
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3 :: Only",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Topic :: Utilities",
        "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = "^3.7"
dataclasses-json="*"

[tool.poetry.dev-dependencies]
# テストコードで利用するため
annofabapi = ">=0.47.0"

# test library
pytest = "*"
pytest-xdist = "*"
pytest-cov = "*"

# format library
isort = "*" # import文をsortするために利用する
autoflake = "*" # 未使用のimport文を削除するために利用する
black = {version = "^21.8b0", allow-prereleases = true} # blackはベータ版なのでこの書き方をしている

# lint library
flake8 = "*"
mypy = "*"
pylint = "*"

# document library
sphinx = "*"
docutils = "*"
# pandasのdocumentationページに近いレイアウトにするためのパッケージ
pydata-sphinx-theme = "*"

typed-ast = "*"


[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120
# `__init__.py`の順番が変わるとエラーになる可能性があるので、スキップする
skip="annofab_3dpc/__init__.py"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"


