from typing import Tuple

# jamo
def compose_jamos(text: str) -> str: ...
def decompose_jamos(text: str) -> str: ...

class JamoSplitter:
    def compose(text: str) -> str: ...
    def decompose(text: str) -> str: ...
    def __repr__() -> str: ...

# distance
def levenshtein_distance(a: str, b: str) -> int: ...
def decomposed_levenshtein_distance(a: str, b: str) -> int: ...
def get_longest_common_substring(a: str, b: str) -> Tuple[int, int]: ...
