
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-01T20:25:20+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "89feb2d8e1e1d5331af4e342d8794df5d1bde2f3",
 "version": "0.4.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
