
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-06T13:51:19+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "0fba25b296e1604518446273623c6de932cfd5b0",
 "version": "0.7.0.post.dev432"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
