[tool.poetry]
name = "CloudConfig"
version = "0.2.1"
description = ""
authors = ["Anton Rastyazhenko <rastyazhenko.anton@gmail.com>"]
repository = "https://github.com/Albus/CloudConfig.git"
homepage = "https://github.com/Albus/CloudConfig"
keywords = ["rancheros", "burmillaos", "config", "json", "http"]
packages = [
    { include = "CloudConfig", from = "src" },
]
[tool.poetry.dependencies]
python = "^3.8"
pydantic = "^1.8.2"
rsa = "^4.7.2"
orjson = "^3.6.3"
pathlib2 = "^2.3.6"
yarl = "^1.6.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
