name: test
on: [push]

jobs:
  test:
    name: python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
      fail-fast: true

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup python ${{ matrix.python-version }} on ${{ matrix.os }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: install deps
      run: python -m pip install tox
    - name: test
      run: python -m tox -p
    - name: upload cov
      uses: codecov/codecov-action@v1
      with:
        files: ./coverage.xml
        fail_ci_if_error: true
        verbose: true
