# coding: utf-8

"""
    Typewise API

    Typewise server for text completion, autocorrection and emoji searching.  # noqa: E501

    OpenAPI spec version: 0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LastWordCorrectionRequestSentence(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'text': 'str',
        'keyboard': 'AllOfLastWordCorrectionRequestSentenceKeyboard',
        'language': 'AllOfLastWordCorrectionRequestSentenceLanguage'
    }

    attribute_map = {
        'text': 'text',
        'keyboard': 'keyboard',
        'language': 'language'
    }

    def __init__(self, text=None, keyboard=None, language=None):  # noqa: E501
        """LastWordCorrectionRequestSentence - a model defined in Swagger"""  # noqa: E501
        self._text = None
        self._keyboard = None
        self._language = None
        self.discriminator = None
        self.text = text
        if keyboard is not None:
            self.keyboard = keyboard
        if language is not None:
            self.language = language

    @property
    def text(self):
        """Gets the text of this LastWordCorrectionRequestSentence.  # noqa: E501

        Sentence with a corrupted final word  # noqa: E501

        :return: The text of this LastWordCorrectionRequestSentence.  # noqa: E501
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this LastWordCorrectionRequestSentence.

        Sentence with a corrupted final word  # noqa: E501

        :param text: The text of this LastWordCorrectionRequestSentence.  # noqa: E501
        :type: str
        """
        if text is None:
            raise ValueError("Invalid value for `text`, must not be `None`")  # noqa: E501

        self._text = text

    @property
    def keyboard(self):
        """Gets the keyboard of this LastWordCorrectionRequestSentence.  # noqa: E501

        Which keyboard layout you are using (QWERTY/QWERTZ/AZERTY)  # noqa: E501

        :return: The keyboard of this LastWordCorrectionRequestSentence.  # noqa: E501
        :rtype: AllOfLastWordCorrectionRequestSentenceKeyboard
        """
        return self._keyboard

    @keyboard.setter
    def keyboard(self, keyboard):
        """Sets the keyboard of this LastWordCorrectionRequestSentence.

        Which keyboard layout you are using (QWERTY/QWERTZ/AZERTY)  # noqa: E501

        :param keyboard: The keyboard of this LastWordCorrectionRequestSentence.  # noqa: E501
        :type: AllOfLastWordCorrectionRequestSentenceKeyboard
        """

        self._keyboard = keyboard

    @property
    def language(self):
        """Gets the language of this LastWordCorrectionRequestSentence.  # noqa: E501

        The language of the sentence (en/de/fr/it/es/pt)  # noqa: E501

        :return: The language of this LastWordCorrectionRequestSentence.  # noqa: E501
        :rtype: AllOfLastWordCorrectionRequestSentenceLanguage
        """
        return self._language

    @language.setter
    def language(self, language):
        """Sets the language of this LastWordCorrectionRequestSentence.

        The language of the sentence (en/de/fr/it/es/pt)  # noqa: E501

        :param language: The language of this LastWordCorrectionRequestSentence.  # noqa: E501
        :type: AllOfLastWordCorrectionRequestSentenceLanguage
        """

        self._language = language

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LastWordCorrectionRequestSentence, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LastWordCorrectionRequestSentence):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
