[tool.poetry]
name = "slant"
version = "0.1.4"
description = "Identify and measure bias in Python"
authors = ["William W. Marx <null@marx.design>"]
license = "CC0 1.0 Universal"

[tool.poetry.dependencies]
python = "^3.6"
numpy = "^1.19.5"
multiprocess = "^0.70.12"

[tool.poetry.dev-dependencies]
yapf = "^0.31.0"
pytest = "^6.2.5"
pylint = "^2.10.2"
vaderSentiment = "^3.3.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
