
app:
  network:
    host: ''
    password: ''
    port: 0
    type: No Proxy
    username: ''
  style:
    theme: Bright

variant_view:
  memory_cache: 32
  rows_per_page: 50
  links:
    - name: "GenCards - The human gene database"
      is_browser: true
      is_default: false
      url: "https://www.genecards.org/cgi-bin/carddisp.pl?gene={{annotations[0].gene}}"
    - name: "Varsome - Genes"
      is_browser: true
      is_default: false
      url: "https://varsome.com/gene/{{annotations[0].gene}}"
    - name: "Varsome - Variants"
      is_browser: true
      is_default: false
      url: "https://varsome.com/variant/hg19/{{chr|replace('chr','')}}-{{pos}}-{{ref}}-{{alt}}"
    - name: "Google - Gene"
      is_browser: true
      is_default: false
      url: "https://google.com/search?q={{annotations[0].gene}}"
    - name: "Google - Gene ID"
      is_browser: true
      is_default: false
      url: "https://google.com/search?q={{annotations[0].gene_id}}"
    - name: "dbSNP"
      is_browser: true
      is_default: false
      url: "https://www.ncbi.nlm.nih.gov/snp/{{rs}}"
    - name: "Clinvar - Allele ID"
      is_browser: true
      is_default: false
      url: "http://www.ncbi.nlm.nih.gov/clinvar/?term={{alleleid}}[alleleid]"
    - name: "IGV"
      is_browser: false
      is_default: false
      url: "http://localhost:60151/goto?locus=chr{{chr|replace('chr','')}}:{{pos}}"
