[tool.poetry]
name = "treex"
version = "0.2.2"
description = ""
authors = ["Cristian Garcia <cgarcia.e88@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.9"
jax = "^0.2.18"
jaxlib = "^0.1.70"
flax = "^0.3.4"
PyYAML = "^5.4.1"
rich = "^10.7.0"
optax = "^0.0.9"

[tool.poetry.dev-dependencies]
matplotlib = "^3.4.3"
pytest = "^5.2"
streambook = "^0.2"
black = {version = "^21.7b0", allow-prereleases = true}
jupyterlab = "^3.1.7"
hypothesis = "^6.14.8"
dataget = "^0.4.15"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
