[tool.poetry]
name = "blinkcheck"
version = "0.1.1"
description = "Basic link checker"
authors = ["Mario Kahlhofer <mario.kahlhofer@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/blu3r4y/pyforever"

[tool.poetry.scripts]
blinkcheck = "blinkcheck.console:main"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
