[tool.poetry]
name = "starsessions"
version = "1.1.0"
description = "Pluggable session support for Starlette."
authors = ["alex.oleshkevich <alex.oleshkevich@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/alex-oleshkevich/starsessions"
repository = "https://github.com/alex-oleshkevich/starsessions"
documentation = "https://github.com/alex-oleshkevich/starsessions"
keywords = ["starlette", "fastapi", "asgi", "session"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Web Environment",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.6",
    "Topic :: Software Development :: Libraries",
    "Typing :: Typed",
]

[tool.poetry.dependencies]
python = "^3.6.2"
starlette = "^0.15.0"
itsdangerous = "^2.0.1"
aioredis = { version = "^2.0.0", optional = true }

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
black = { version = "^21.6b0", allow-prereleases = true }
pytest-asyncio = "^0.15.1"
requests = "^2.25.1"
pytest-coverage = "^0.0"
flake8 = "^3.9.2"
mypy = "^0.910"
aioredis = "^2.0.0"

[tool.poetry.extras]
redis = ["aioredis"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
norecursedirs = [".git", ".venv"]
addopts = "--tb=short -s"
testpaths = ["tests"]
