[tool.poetry]
name = "gnista-library"
version = "1.0.0"
description = "A client library for accessing gnitsa.io"

authors = []

readme = "README.md"
packages = [
    {include = "data_point_client"},
    {include = "gnista_library"},
]
include = ["CHANGELOG.md", "data_point_client/py.typed"]


[tool.poetry.dependencies]
python = "^3.8"
httpx = ">=0.15.4,<0.19.0"
attrs = ">=20.1.0,<22.0.0"
python-dateutil = "^2.8.0"
pandas = "^1.3.2"
oauth2-client = "^1.2.1"
PyJWT = "^2.1.0"
structlog = "^21.1.0"
colorama = "^0.4.4"

[tool.black]
line-length = 120
target_version = ['py38']
exclude = '''
(
  /(
    | \.git
    | \.venv
    | \.mypy_cache
  )/
)
'''

[tool.isort]
line_length = 120
multi_line_output = 3
include_trailing_comma = true

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"