# coding: utf-8

"""
    Typewise API

    Typewise server for text completion, autocorrection and emoji searching.  # noqa: E501

    OpenAPI spec version: 0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from typewiseprediction.api_client import ApiClient


class CorrectionApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def complete_correction_correction_whole_sentence_post(self, body, **kwargs):  # noqa: E501
        """Complete Correction  # noqa: E501

        Correct a complete text  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.complete_correction_correction_whole_sentence_post(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param CompleteCorrectionRequestSentence body: (required)
        :return: CompleteCorrectionReply
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.complete_correction_correction_whole_sentence_post_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.complete_correction_correction_whole_sentence_post_with_http_info(body, **kwargs)  # noqa: E501
            return data

    def complete_correction_correction_whole_sentence_post_with_http_info(self, body, **kwargs):  # noqa: E501
        """Complete Correction  # noqa: E501

        Correct a complete text  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.complete_correction_correction_whole_sentence_post_with_http_info(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param CompleteCorrectionRequestSentence body: (required)
        :return: CompleteCorrectionReply
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method complete_correction_correction_whole_sentence_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `complete_correction_correction_whole_sentence_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/correction/whole_sentence', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='CompleteCorrectionReply',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def complete_correction_correction_whole_sentence_post_0(self, body, **kwargs):  # noqa: E501
        """Complete Correction  # noqa: E501

        Correct a complete text  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.complete_correction_correction_whole_sentence_post_0(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param CompleteCorrectionRequestSentence body: (required)
        :return: CompleteCorrectionReply
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.complete_correction_correction_whole_sentence_post_0_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.complete_correction_correction_whole_sentence_post_0_with_http_info(body, **kwargs)  # noqa: E501
            return data

    def complete_correction_correction_whole_sentence_post_0_with_http_info(self, body, **kwargs):  # noqa: E501
        """Complete Correction  # noqa: E501

        Correct a complete text  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.complete_correction_correction_whole_sentence_post_0_with_http_info(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param CompleteCorrectionRequestSentence body: (required)
        :return: CompleteCorrectionReply
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method complete_correction_correction_whole_sentence_post_0" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `complete_correction_correction_whole_sentence_post_0`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/correction/whole_sentence', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='CompleteCorrectionReply',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def complete_correction_correction_whole_sentence_post_1(self, body, **kwargs):  # noqa: E501
        """Complete Correction  # noqa: E501

        Correct a complete text  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.complete_correction_correction_whole_sentence_post_1(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param CompleteCorrectionRequestSentence body: (required)
        :return: CompleteCorrectionReply
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.complete_correction_correction_whole_sentence_post_1_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.complete_correction_correction_whole_sentence_post_1_with_http_info(body, **kwargs)  # noqa: E501
            return data

    def complete_correction_correction_whole_sentence_post_1_with_http_info(self, body, **kwargs):  # noqa: E501
        """Complete Correction  # noqa: E501

        Correct a complete text  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.complete_correction_correction_whole_sentence_post_1_with_http_info(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param CompleteCorrectionRequestSentence body: (required)
        :return: CompleteCorrectionReply
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method complete_correction_correction_whole_sentence_post_1" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `complete_correction_correction_whole_sentence_post_1`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/correction/whole_sentence', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='CompleteCorrectionReply',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def last_word_correction_correction_final_word_post(self, body, **kwargs):  # noqa: E501
        """Last Word Correction  # noqa: E501

        Correct a single word  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.last_word_correction_correction_final_word_post(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param LastWordCorrectionRequestSentence body: (required)
        :return: LastWordCorrectionReply
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.last_word_correction_correction_final_word_post_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.last_word_correction_correction_final_word_post_with_http_info(body, **kwargs)  # noqa: E501
            return data

    def last_word_correction_correction_final_word_post_with_http_info(self, body, **kwargs):  # noqa: E501
        """Last Word Correction  # noqa: E501

        Correct a single word  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.last_word_correction_correction_final_word_post_with_http_info(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param LastWordCorrectionRequestSentence body: (required)
        :return: LastWordCorrectionReply
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method last_word_correction_correction_final_word_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `last_word_correction_correction_final_word_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/correction/final_word', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='LastWordCorrectionReply',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def last_word_correction_correction_final_word_post_0(self, body, **kwargs):  # noqa: E501
        """Last Word Correction  # noqa: E501

        Correct a single word  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.last_word_correction_correction_final_word_post_0(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param LastWordCorrectionRequestSentence body: (required)
        :return: LastWordCorrectionReply
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.last_word_correction_correction_final_word_post_0_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.last_word_correction_correction_final_word_post_0_with_http_info(body, **kwargs)  # noqa: E501
            return data

    def last_word_correction_correction_final_word_post_0_with_http_info(self, body, **kwargs):  # noqa: E501
        """Last Word Correction  # noqa: E501

        Correct a single word  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.last_word_correction_correction_final_word_post_0_with_http_info(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param LastWordCorrectionRequestSentence body: (required)
        :return: LastWordCorrectionReply
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method last_word_correction_correction_final_word_post_0" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `last_word_correction_correction_final_word_post_0`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/correction/final_word', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='LastWordCorrectionReply',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def last_word_correction_correction_final_word_post_1(self, body, **kwargs):  # noqa: E501
        """Last Word Correction  # noqa: E501

        Correct a single word  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.last_word_correction_correction_final_word_post_1(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param LastWordCorrectionRequestSentence body: (required)
        :return: LastWordCorrectionReply
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.last_word_correction_correction_final_word_post_1_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.last_word_correction_correction_final_word_post_1_with_http_info(body, **kwargs)  # noqa: E501
            return data

    def last_word_correction_correction_final_word_post_1_with_http_info(self, body, **kwargs):  # noqa: E501
        """Last Word Correction  # noqa: E501

        Correct a single word  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.last_word_correction_correction_final_word_post_1_with_http_info(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param LastWordCorrectionRequestSentence body: (required)
        :return: LastWordCorrectionReply
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method last_word_correction_correction_final_word_post_1" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `last_word_correction_correction_final_word_post_1`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/correction/final_word', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='LastWordCorrectionReply',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
