__title__ = "honeycomb"
__description__ = "Multi-source/engine querying tool"
__url__ = "https://github.com/neighborhoods/honeycomb"
__version__ = "1.7.1"
__author__ = "George Wood (@Geoiv)"
__author_email__ = "george.wood@55places.com"
