
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-03T10:29:01+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "1bffc9213f4e1ce8c68c243c6376bf9c90217ad9",
 "version": "2021.09.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
