
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-31T00:23:54+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b4e3b7e8163d11cee3e7fbaa7eeae1f86ddf29c5",
 "version": "0.3.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
