[tool.poetry]
name = "figvis"
version = "0.1.0-alpha.7"
description = "Figment Visualization is a framework to visualize data using templates"
authors = ["Umesh Mohan <moh@nume.sh>"]
repository = "https://gitlab.com/u-m/figvis"
readme = "README.rst"

[tool.poetry.scripts]
figvis = "figvis.cli.main:app"

[tool.poetry.dependencies]
python = "^3.9"
typer = "^0.3.2"
Jinja2 = "^3.0.1"
selenium = ">=4.0.0.b4"
lxml = "^4.6.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
