# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/payment/definition.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='api/payment/definition.proto',
  package='ivi.proto.api.payment',
  syntax='proto3',
  serialized_options=b'\n(games.mythical.ivi.sdk.proto.api.paymentP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1c\x61pi/payment/definition.proto\x12\x15ivi.proto.api.payment\"{\n\x12\x43reateTokenRequest\x12\x16\n\x0e\x65nvironment_id\x18\x01 \x01(\t\x12\x41\n\tbraintree\x18\x02 \x01(\x0b\x32,.ivi.proto.api.payment.BraintreeTokenRequestH\x00\x42\n\n\x08provider\"*\n\x15\x42raintreeTokenRequest\x12\x11\n\tplayer_id\x18\x01 \x01(\t\"O\n\x05Token\x12:\n\tbraintree\x18\x01 \x01(\x0b\x32%.ivi.proto.api.payment.BraintreeTokenH\x00\x42\n\n\x08provider\"\x1f\n\x0e\x42raintreeToken\x12\r\n\x05token\x18\x01 \x01(\tB,\n(games.mythical.ivi.sdk.proto.api.paymentP\x01\x62\x06proto3'
)




_CREATETOKENREQUEST = _descriptor.Descriptor(
  name='CreateTokenRequest',
  full_name='ivi.proto.api.payment.CreateTokenRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='environment_id', full_name='ivi.proto.api.payment.CreateTokenRequest.environment_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='braintree', full_name='ivi.proto.api.payment.CreateTokenRequest.braintree', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='provider', full_name='ivi.proto.api.payment.CreateTokenRequest.provider',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=55,
  serialized_end=178,
)


_BRAINTREETOKENREQUEST = _descriptor.Descriptor(
  name='BraintreeTokenRequest',
  full_name='ivi.proto.api.payment.BraintreeTokenRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='player_id', full_name='ivi.proto.api.payment.BraintreeTokenRequest.player_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=222,
)


_TOKEN = _descriptor.Descriptor(
  name='Token',
  full_name='ivi.proto.api.payment.Token',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='braintree', full_name='ivi.proto.api.payment.Token.braintree', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='provider', full_name='ivi.proto.api.payment.Token.provider',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=224,
  serialized_end=303,
)


_BRAINTREETOKEN = _descriptor.Descriptor(
  name='BraintreeToken',
  full_name='ivi.proto.api.payment.BraintreeToken',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='ivi.proto.api.payment.BraintreeToken.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=305,
  serialized_end=336,
)

_CREATETOKENREQUEST.fields_by_name['braintree'].message_type = _BRAINTREETOKENREQUEST
_CREATETOKENREQUEST.oneofs_by_name['provider'].fields.append(
  _CREATETOKENREQUEST.fields_by_name['braintree'])
_CREATETOKENREQUEST.fields_by_name['braintree'].containing_oneof = _CREATETOKENREQUEST.oneofs_by_name['provider']
_TOKEN.fields_by_name['braintree'].message_type = _BRAINTREETOKEN
_TOKEN.oneofs_by_name['provider'].fields.append(
  _TOKEN.fields_by_name['braintree'])
_TOKEN.fields_by_name['braintree'].containing_oneof = _TOKEN.oneofs_by_name['provider']
DESCRIPTOR.message_types_by_name['CreateTokenRequest'] = _CREATETOKENREQUEST
DESCRIPTOR.message_types_by_name['BraintreeTokenRequest'] = _BRAINTREETOKENREQUEST
DESCRIPTOR.message_types_by_name['Token'] = _TOKEN
DESCRIPTOR.message_types_by_name['BraintreeToken'] = _BRAINTREETOKEN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateTokenRequest = _reflection.GeneratedProtocolMessageType('CreateTokenRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATETOKENREQUEST,
  '__module__' : 'api.payment.definition_pb2'
  # @@protoc_insertion_point(class_scope:ivi.proto.api.payment.CreateTokenRequest)
  })
_sym_db.RegisterMessage(CreateTokenRequest)

BraintreeTokenRequest = _reflection.GeneratedProtocolMessageType('BraintreeTokenRequest', (_message.Message,), {
  'DESCRIPTOR' : _BRAINTREETOKENREQUEST,
  '__module__' : 'api.payment.definition_pb2'
  # @@protoc_insertion_point(class_scope:ivi.proto.api.payment.BraintreeTokenRequest)
  })
_sym_db.RegisterMessage(BraintreeTokenRequest)

Token = _reflection.GeneratedProtocolMessageType('Token', (_message.Message,), {
  'DESCRIPTOR' : _TOKEN,
  '__module__' : 'api.payment.definition_pb2'
  # @@protoc_insertion_point(class_scope:ivi.proto.api.payment.Token)
  })
_sym_db.RegisterMessage(Token)

BraintreeToken = _reflection.GeneratedProtocolMessageType('BraintreeToken', (_message.Message,), {
  'DESCRIPTOR' : _BRAINTREETOKEN,
  '__module__' : 'api.payment.definition_pb2'
  # @@protoc_insertion_point(class_scope:ivi.proto.api.payment.BraintreeToken)
  })
_sym_db.RegisterMessage(BraintreeToken)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
