
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-02T09:41:01-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "c98e72090320a265b80fdaf3546495903529f1bb",
 "version": "0.13.32"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
