from . import DesignUtilities

print("\033[31m" + "tkinter_expansion CRITICAL WARNING!")
print("DO NOT USE THIS FOR NORMAL USE OR OTHERWISE SOMEONE COULD HACK YOUR APPLICATION BECAUSE OF EXEC!"
      " THIS IS NOT SECURE AT ALL!"
      " AND YOUR APP MIGHT SOMETIMES CRASH BECAUSE OF UNSTABLE CODE!" + "\033[0m")
