[tool.poetry]
name = "quack-cli"
version = "0.1.0"
description = "A CLI for the Quackstack API"
authors = ["Kronifer <44979306+Kronifer@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
typer = "^0.4"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
