
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-05T12:12:11-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "9bc4ceaf30f5f528b6e2d353f85216a5821a63f7",
 "version": "v0.2.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
