
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-03T17:13:41+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "f0d67686c6788f0e46a016764ab3dc96b9217453",
 "version": "0.2.25"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
