language: python

branches:
  only:
    - master
    - dev

dist: xenial

python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install codecov
  - make install

# Runs unit tests and generates coverage report
script: make tests

after_success: codecov