# Generated by Django 3.2.6 on 2021-08-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref_id', models.IntegerField(blank=True, editable=False, null=True)),
            ],
        ),
    ]
