[tool.poetry]
name = "tex_engine"
version = "0.1.0"
description = "Template Engine X. Have fun with HTML"
authors = ["Leo B. <bernerdoodle@outlook.de>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
