# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streams/common.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='streams/common.proto',
  package='ivi.rpc.streams',
  syntax='proto3',
  serialized_options=b'\n$games.mythical.ivi.sdk.proto.streamsP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14streams/common.proto\x12\x0fivi.rpc.streams\"#\n\tSubscribe\x12\x16\n\x0e\x65nvironment_id\x18\x01 \x01(\tB(\n$games.mythical.ivi.sdk.proto.streamsP\x01\x62\x06proto3'
)




_SUBSCRIBE = _descriptor.Descriptor(
  name='Subscribe',
  full_name='ivi.rpc.streams.Subscribe',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='environment_id', full_name='ivi.rpc.streams.Subscribe.environment_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=76,
)

DESCRIPTOR.message_types_by_name['Subscribe'] = _SUBSCRIBE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Subscribe = _reflection.GeneratedProtocolMessageType('Subscribe', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBE,
  '__module__' : 'streams.common_pb2'
  # @@protoc_insertion_point(class_scope:ivi.rpc.streams.Subscribe)
  })
_sym_db.RegisterMessage(Subscribe)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
