# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: deepconsensus/protos/deepconsensus.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from nucleus.protos import bed_pb2 as nucleus_dot_protos_dot_bed__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='deepconsensus/protos/deepconsensus.proto',
  package='deepconsensus',
  syntax='proto3',
  serialized_pb=_b('\n(deepconsensus/protos/deepconsensus.proto\x12\rdeepconsensus\x1a\x18nucleus/protos/bed.proto\"\x90\x02\n\x07Subread\x12\x15\n\rmolecule_name\x18\x01 \x01(\t\x12\r\n\x05\x62\x61ses\x18\x02 \x01(\t\x12\x16\n\x0e\x65xpanded_cigar\x18\x03 \x01(\t\x12\n\n\x02pw\x18\x04 \x03(\x05\x12\n\n\x02ip\x18\x05 \x03(\x05\x12\x16\n\x0e\x62\x61se_positions\x18\x06 \x03(\x05\x12\x17\n\x0fsubread_indices\x18\x07 \x03(\x05\x12@\n\x0esubread_strand\x18\x08 \x01(\x0e\x32(.deepconsensus.Subread.SubreadStrandEnum\"<\n\x11SubreadStrandEnum\x12\r\n\tNO_STRAND\x10\x00\x12\x0b\n\x07\x46ORWARD\x10\x01\x12\x0b\n\x07REVERSE\x10\x02\"\xb6\x04\n\x12\x44\x65\x65pConsensusInput\x12(\n\x08subreads\x18\x01 \x03(\x0b\x32\x16.deepconsensus.Subread\x12%\n\x05label\x18\x02 \x01(\x0b\x32\x16.deepconsensus.Subread\x12\x15\n\rmolecule_name\x18\x03 \x01(\t\x12\x16\n\x0emolecule_start\x18\x04 \x01(\x05\x12\x12\n\nchrom_name\x18\x05 \x01(\t\x12\x13\n\x0b\x63hrom_start\x18\x06 \x01(\x05\x12\x11\n\tchrom_end\x18\x07 \x01(\x05\x12\n\n\x02sn\x18\x08 \x03(\x02\x12\x35\n\x06strand\x18\t \x01(\x0e\x32%.nucleus.genomics.v1.BedRecord.Strand\x12 \n\x18\x64\x65\x65pconsensus_prediction\x18\n \x01(\t\x12\x17\n\x0fsubread_indices\x18\x0b \x03(\x05\x12\x14\n\x0c\x63\x63s_sequence\x18\x0c \x01(\t\x12\\\n\x17unsup_insertions_by_pos\x18\r \x03(\x0b\x32;.deepconsensus.DeepConsensusInput.UnsupInsertionsByPosEntry\x12\x1d\n\x15unsup_insertion_count\x18\x0e \x01(\x05\x12\x16\n\x0equality_string\x18\x0f \x01(\t\x1a;\n\x19UnsupInsertionsByPosEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x62\x06proto3')
  ,
  dependencies=[nucleus_dot_protos_dot_bed__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SUBREAD_SUBREADSTRANDENUM = _descriptor.EnumDescriptor(
  name='SubreadStrandEnum',
  full_name='deepconsensus.Subread.SubreadStrandEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_STRAND', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FORWARD', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REVERSE', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=298,
  serialized_end=358,
)
_sym_db.RegisterEnumDescriptor(_SUBREAD_SUBREADSTRANDENUM)


_SUBREAD = _descriptor.Descriptor(
  name='Subread',
  full_name='deepconsensus.Subread',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='molecule_name', full_name='deepconsensus.Subread.molecule_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bases', full_name='deepconsensus.Subread.bases', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='expanded_cigar', full_name='deepconsensus.Subread.expanded_cigar', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pw', full_name='deepconsensus.Subread.pw', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ip', full_name='deepconsensus.Subread.ip', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='base_positions', full_name='deepconsensus.Subread.base_positions', index=5,
      number=6, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subread_indices', full_name='deepconsensus.Subread.subread_indices', index=6,
      number=7, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subread_strand', full_name='deepconsensus.Subread.subread_strand', index=7,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SUBREAD_SUBREADSTRANDENUM,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=358,
)


_DEEPCONSENSUSINPUT_UNSUPINSERTIONSBYPOSENTRY = _descriptor.Descriptor(
  name='UnsupInsertionsByPosEntry',
  full_name='deepconsensus.DeepConsensusInput.UnsupInsertionsByPosEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='deepconsensus.DeepConsensusInput.UnsupInsertionsByPosEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='deepconsensus.DeepConsensusInput.UnsupInsertionsByPosEntry.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=868,
  serialized_end=927,
)

_DEEPCONSENSUSINPUT = _descriptor.Descriptor(
  name='DeepConsensusInput',
  full_name='deepconsensus.DeepConsensusInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subreads', full_name='deepconsensus.DeepConsensusInput.subreads', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='label', full_name='deepconsensus.DeepConsensusInput.label', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='molecule_name', full_name='deepconsensus.DeepConsensusInput.molecule_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='molecule_start', full_name='deepconsensus.DeepConsensusInput.molecule_start', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chrom_name', full_name='deepconsensus.DeepConsensusInput.chrom_name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chrom_start', full_name='deepconsensus.DeepConsensusInput.chrom_start', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chrom_end', full_name='deepconsensus.DeepConsensusInput.chrom_end', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sn', full_name='deepconsensus.DeepConsensusInput.sn', index=7,
      number=8, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='strand', full_name='deepconsensus.DeepConsensusInput.strand', index=8,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deepconsensus_prediction', full_name='deepconsensus.DeepConsensusInput.deepconsensus_prediction', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subread_indices', full_name='deepconsensus.DeepConsensusInput.subread_indices', index=10,
      number=11, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ccs_sequence', full_name='deepconsensus.DeepConsensusInput.ccs_sequence', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unsup_insertions_by_pos', full_name='deepconsensus.DeepConsensusInput.unsup_insertions_by_pos', index=12,
      number=13, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unsup_insertion_count', full_name='deepconsensus.DeepConsensusInput.unsup_insertion_count', index=13,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='quality_string', full_name='deepconsensus.DeepConsensusInput.quality_string', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DEEPCONSENSUSINPUT_UNSUPINSERTIONSBYPOSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=361,
  serialized_end=927,
)

_SUBREAD.fields_by_name['subread_strand'].enum_type = _SUBREAD_SUBREADSTRANDENUM
_SUBREAD_SUBREADSTRANDENUM.containing_type = _SUBREAD
_DEEPCONSENSUSINPUT_UNSUPINSERTIONSBYPOSENTRY.containing_type = _DEEPCONSENSUSINPUT
_DEEPCONSENSUSINPUT.fields_by_name['subreads'].message_type = _SUBREAD
_DEEPCONSENSUSINPUT.fields_by_name['label'].message_type = _SUBREAD
_DEEPCONSENSUSINPUT.fields_by_name['strand'].enum_type = nucleus_dot_protos_dot_bed__pb2._BEDRECORD_STRAND
_DEEPCONSENSUSINPUT.fields_by_name['unsup_insertions_by_pos'].message_type = _DEEPCONSENSUSINPUT_UNSUPINSERTIONSBYPOSENTRY
DESCRIPTOR.message_types_by_name['Subread'] = _SUBREAD
DESCRIPTOR.message_types_by_name['DeepConsensusInput'] = _DEEPCONSENSUSINPUT

Subread = _reflection.GeneratedProtocolMessageType('Subread', (_message.Message,), dict(
  DESCRIPTOR = _SUBREAD,
  __module__ = 'deepconsensus.protos.deepconsensus_pb2'
  # @@protoc_insertion_point(class_scope:deepconsensus.Subread)
  ))
_sym_db.RegisterMessage(Subread)

DeepConsensusInput = _reflection.GeneratedProtocolMessageType('DeepConsensusInput', (_message.Message,), dict(

  UnsupInsertionsByPosEntry = _reflection.GeneratedProtocolMessageType('UnsupInsertionsByPosEntry', (_message.Message,), dict(
    DESCRIPTOR = _DEEPCONSENSUSINPUT_UNSUPINSERTIONSBYPOSENTRY,
    __module__ = 'deepconsensus.protos.deepconsensus_pb2'
    # @@protoc_insertion_point(class_scope:deepconsensus.DeepConsensusInput.UnsupInsertionsByPosEntry)
    ))
  ,
  DESCRIPTOR = _DEEPCONSENSUSINPUT,
  __module__ = 'deepconsensus.protos.deepconsensus_pb2'
  # @@protoc_insertion_point(class_scope:deepconsensus.DeepConsensusInput)
  ))
_sym_db.RegisterMessage(DeepConsensusInput)
_sym_db.RegisterMessage(DeepConsensusInput.UnsupInsertionsByPosEntry)


_DEEPCONSENSUSINPUT_UNSUPINSERTIONSBYPOSENTRY.has_options = True
_DEEPCONSENSUSINPUT_UNSUPINSERTIONSBYPOSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
