[tool.poetry]
name = "pieoffice"
version = "1.3.2"
description = "A terminal based script converter for ancient (Proto-)Indo-European languages."
authors = ["Caio Geraldes <caio.geraldes@usp.br>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"
betacode = "^1.0"
docopt = "^0.6.2"
pygtrie = "^2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
