
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-02T19:48:48+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9661d588a0a57a7b916670a080c9b05ebc4acb70",
 "version": "2.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
