# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from ivi_sdk.streams import common_pb2 as streams_dot_common__pb2
from ivi_sdk.streams.player import stream_pb2 as streams_dot_player_dot_stream__pb2


class PlayerStreamStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PlayerStatusStream = channel.unary_stream(
                '/ivi.rpc.streams.player.PlayerStream/PlayerStatusStream',
                request_serializer=streams_dot_common__pb2.Subscribe.SerializeToString,
                response_deserializer=streams_dot_player_dot_stream__pb2.PlayerStatusUpdate.FromString,
                )
        self.PlayerStatusConfirmation = channel.unary_unary(
                '/ivi.rpc.streams.player.PlayerStream/PlayerStatusConfirmation',
                request_serializer=streams_dot_player_dot_stream__pb2.PlayerStatusConfirmRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class PlayerStreamServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PlayerStatusStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlayerStatusConfirmation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlayerStreamServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PlayerStatusStream': grpc.unary_stream_rpc_method_handler(
                    servicer.PlayerStatusStream,
                    request_deserializer=streams_dot_common__pb2.Subscribe.FromString,
                    response_serializer=streams_dot_player_dot_stream__pb2.PlayerStatusUpdate.SerializeToString,
            ),
            'PlayerStatusConfirmation': grpc.unary_unary_rpc_method_handler(
                    servicer.PlayerStatusConfirmation,
                    request_deserializer=streams_dot_player_dot_stream__pb2.PlayerStatusConfirmRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ivi.rpc.streams.player.PlayerStream', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PlayerStream(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PlayerStatusStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ivi.rpc.streams.player.PlayerStream/PlayerStatusStream',
            streams_dot_common__pb2.Subscribe.SerializeToString,
            streams_dot_player_dot_stream__pb2.PlayerStatusUpdate.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PlayerStatusConfirmation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ivi.rpc.streams.player.PlayerStream/PlayerStatusConfirmation',
            streams_dot_player_dot_stream__pb2.PlayerStatusConfirmRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
