
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-02T12:58:15-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "ab0e88618e2fae7d93fd05cae49b963ce53a7f99",
 "version": "v1.5.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
