
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-31T11:23:06+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "11e90bfd65eff87af994bbc8019cf94f54ec84dd",
 "version": "0.4.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
