# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, devel, smac_bo ]
  pull_request:
    branches: [ master, devel ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-10.15]
        python-version: [3.6, 3.8]
    steps:
      - name: Cancel previous runs.
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout.
        uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies for tests.
        run: |
          pip3 install coverage
          pip3 install codecov
          pip3 install pycodestyle
          pip3 install numpy==1.19.4
          pip3 install GPy
          pip3 install GPyOpt
          pip3 install pandas
          pip3 install ruamel.yaml==0.16.12
          pip3 install pytest
          pip3 install pytest-cov
          pip3 install pytest-timeout

      - name: Upgrade NumPy for Python 3.8.
        run: |
          pip3 install --upgrade numpy
        if: matrix.python-version == 3.8

      - name: Install GADMA and its dependencies (Linux and MacOS).
        run: |
          ./install
        if: matrix.os != 'windows-2019'

      - name: Install GADMA and its dependencies (Windows).
        run: |
          bash install
          python -c "import moments"
        shell: cmd
        if: matrix.os == 'windows-2019'

      - name: Install SMAC (Linux).
        run: |
          pip3 install scikit-optimize
          pip3 install configspace
          pip3 install smac==0.12.4
          pip3 install bayesmark
        if: matrix.os == 'ubuntu-18.04'
      - name: Downgrade scipy for SMAC (Linux).
        run: |
          pip3 install scipy==1.6.3
        if: matrix.os == 'ubuntu-18.04' && matrix.python-version == '3.8'

      - name: Run tests and codecov.
        run: |
          python -m pytest --timeout=400 --cov=gadma --cov-report=xml -v tests --disable-warnings
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
        if: matrix.os == 'ubuntu-18.04' && matrix.python-version == '3.6'

