# Generated by Django 3.2.6 on 2021-08-28 17:29

import dj_ingredient_field
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', dj_ingredient_field.IngredientField()),
                ('unit', dj_ingredient_field.MeasurementUnitField()),
                ('amount', models.FloatField()),
            ],
        ),
    ]
