# Generated by Django 3.2.6 on 2021-08-29 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_ingredient_field', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientQuantity',
            new_name='MyModel',
        ),
    ]
