
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-03T12:13:10+0900",
 "dirty": true,
 "error": null,
 "full-revisionid": "e81c475dcac7d4700fcb42db620bae337022a25b",
 "version": "0.9.0+7.ge81c475.dirty"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
