
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-02T11:10:48+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1ce352d0f7e047f346b26f9f48ccc51b7042bce0",
 "version": "0.7.0.post.dev430"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
