#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['nkdfu']

package_data = \
{'': ['*']}

install_requires = \
['fire', 'tqdm', 'intelhex >= 2.3.0', 'libusb1 >= 1.9.3']

entry_points = \
{'console_scripts': ['nkdfu = nkdfu.dfu_flash:cli']}

setup(name='nkdfu',
      version='0.1',
      description="DFU tool for updating Nitrokeys' firmware",
      author='Nitrokey',
      author_email='pypi@nitrokey.com',
      url='https://github.com/Nitrokey/nkdfu',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      entry_points=entry_points,
      python_requires='>=3.6',
     )
