# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streams/itemtype/stream.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from ivi_sdk.streams import common_pb2 as streams_dot_common__pb2
from ivi_sdk.common.itemtype import definition_pb2 as common_dot_itemtype_dot_definition__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='streams/itemtype/stream.proto',
  package='ivi.rpc.streams.itemtype',
  syntax='proto3',
  serialized_options=b'\n-games.mythical.ivi.sdk.proto.streams.itemtypeP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1dstreams/itemtype/stream.proto\x12\x18ivi.rpc.streams.itemtype\x1a\x1bgoogle/protobuf/empty.proto\x1a\x14streams/common.proto\x1a common/itemtype/definition.proto\"\xe3\x01\n\x14ItemTypeStatusUpdate\x12\x19\n\x11game_item_type_id\x18\x01 \x01(\t\x12\x16\n\x0e\x63urrent_supply\x18\x02 \x01(\x05\x12\x15\n\rissued_supply\x18\x03 \x01(\x05\x12\x10\n\x08\x62\x61se_uri\x18\x04 \x01(\t\x12\x17\n\x0fissue_time_span\x18\x05 \x01(\x05\x12\x13\n\x0btracking_id\x18\x06 \x01(\t\x12\x41\n\x0fitem_type_state\x18\x07 \x01(\x0e\x32(.ivi.proto.common.itemtype.ItemTypeState\"\xa9\x01\n\x1cItemTypeStatusConfirmRequest\x12\x16\n\x0e\x65nvironment_id\x18\x01 \x01(\t\x12\x19\n\x11game_item_type_id\x18\x02 \x01(\t\x12\x13\n\x0btracking_id\x18\x03 \x01(\t\x12\x41\n\x0fitem_type_state\x18\x04 \x01(\x0e\x32(.ivi.proto.common.itemtype.ItemTypeState2\xea\x01\n\x14ItemTypeStatusStream\x12\x64\n\x14ItemTypeStatusStream\x12\x1a.ivi.rpc.streams.Subscribe\x1a..ivi.rpc.streams.itemtype.ItemTypeStatusUpdate0\x01\x12l\n\x1aItemTypeStatusConfirmation\x12\x36.ivi.rpc.streams.itemtype.ItemTypeStatusConfirmRequest\x1a\x16.google.protobuf.EmptyB1\n-games.mythical.ivi.sdk.proto.streams.itemtypeP\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,streams_dot_common__pb2.DESCRIPTOR,common_dot_itemtype_dot_definition__pb2.DESCRIPTOR,])




_ITEMTYPESTATUSUPDATE = _descriptor.Descriptor(
  name='ItemTypeStatusUpdate',
  full_name='ivi.rpc.streams.itemtype.ItemTypeStatusUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='game_item_type_id', full_name='ivi.rpc.streams.itemtype.ItemTypeStatusUpdate.game_item_type_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='current_supply', full_name='ivi.rpc.streams.itemtype.ItemTypeStatusUpdate.current_supply', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='issued_supply', full_name='ivi.rpc.streams.itemtype.ItemTypeStatusUpdate.issued_supply', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='base_uri', full_name='ivi.rpc.streams.itemtype.ItemTypeStatusUpdate.base_uri', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='issue_time_span', full_name='ivi.rpc.streams.itemtype.ItemTypeStatusUpdate.issue_time_span', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tracking_id', full_name='ivi.rpc.streams.itemtype.ItemTypeStatusUpdate.tracking_id', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='item_type_state', full_name='ivi.rpc.streams.itemtype.ItemTypeStatusUpdate.item_type_state', index=6,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=372,
)


_ITEMTYPESTATUSCONFIRMREQUEST = _descriptor.Descriptor(
  name='ItemTypeStatusConfirmRequest',
  full_name='ivi.rpc.streams.itemtype.ItemTypeStatusConfirmRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='environment_id', full_name='ivi.rpc.streams.itemtype.ItemTypeStatusConfirmRequest.environment_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='game_item_type_id', full_name='ivi.rpc.streams.itemtype.ItemTypeStatusConfirmRequest.game_item_type_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tracking_id', full_name='ivi.rpc.streams.itemtype.ItemTypeStatusConfirmRequest.tracking_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='item_type_state', full_name='ivi.rpc.streams.itemtype.ItemTypeStatusConfirmRequest.item_type_state', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=375,
  serialized_end=544,
)

_ITEMTYPESTATUSUPDATE.fields_by_name['item_type_state'].enum_type = common_dot_itemtype_dot_definition__pb2._ITEMTYPESTATE
_ITEMTYPESTATUSCONFIRMREQUEST.fields_by_name['item_type_state'].enum_type = common_dot_itemtype_dot_definition__pb2._ITEMTYPESTATE
DESCRIPTOR.message_types_by_name['ItemTypeStatusUpdate'] = _ITEMTYPESTATUSUPDATE
DESCRIPTOR.message_types_by_name['ItemTypeStatusConfirmRequest'] = _ITEMTYPESTATUSCONFIRMREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ItemTypeStatusUpdate = _reflection.GeneratedProtocolMessageType('ItemTypeStatusUpdate', (_message.Message,), {
  'DESCRIPTOR' : _ITEMTYPESTATUSUPDATE,
  '__module__' : 'streams.itemtype.stream_pb2'
  # @@protoc_insertion_point(class_scope:ivi.rpc.streams.itemtype.ItemTypeStatusUpdate)
  })
_sym_db.RegisterMessage(ItemTypeStatusUpdate)

ItemTypeStatusConfirmRequest = _reflection.GeneratedProtocolMessageType('ItemTypeStatusConfirmRequest', (_message.Message,), {
  'DESCRIPTOR' : _ITEMTYPESTATUSCONFIRMREQUEST,
  '__module__' : 'streams.itemtype.stream_pb2'
  # @@protoc_insertion_point(class_scope:ivi.rpc.streams.itemtype.ItemTypeStatusConfirmRequest)
  })
_sym_db.RegisterMessage(ItemTypeStatusConfirmRequest)


DESCRIPTOR._options = None

_ITEMTYPESTATUSSTREAM = _descriptor.ServiceDescriptor(
  name='ItemTypeStatusStream',
  full_name='ivi.rpc.streams.itemtype.ItemTypeStatusStream',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=547,
  serialized_end=781,
  methods=[
  _descriptor.MethodDescriptor(
    name='ItemTypeStatusStream',
    full_name='ivi.rpc.streams.itemtype.ItemTypeStatusStream.ItemTypeStatusStream',
    index=0,
    containing_service=None,
    input_type=streams_dot_common__pb2._SUBSCRIBE,
    output_type=_ITEMTYPESTATUSUPDATE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ItemTypeStatusConfirmation',
    full_name='ivi.rpc.streams.itemtype.ItemTypeStatusStream.ItemTypeStatusConfirmation',
    index=1,
    containing_service=None,
    input_type=_ITEMTYPESTATUSCONFIRMREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ITEMTYPESTATUSSTREAM)

DESCRIPTOR.services_by_name['ItemTypeStatusStream'] = _ITEMTYPESTATUSSTREAM

# @@protoc_insertion_point(module_scope)
