
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-14T14:11:29-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "503d9ade5af5531207b4b623816dd9bf4ac3e235",
 "version": "0.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
