[tool.poetry]
name = "dabapush"
version = "0.1.4"
description = ""
authors = ["Felix Victor Münch <f.muench@leibniz-hbi.de>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/Leibniz-HBI/dabapush"
classifiers = [
		"Development Status :: 2 - Pre-Alpha",
		"Environment :: Console",
		"Intended Audience :: Science/Research",
]

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.0.0"
SQLAlchemy = "^1.4.22"
loguru = "^0.5.3"
pandas = "^1.3.1"
PyYAML = "^5.4.1"

[tool.poetry.dev-dependencies]
pytest = "*"
flake8 = "*"

[tool.poetry.scripts]
dabapush = 'dabapush.dabapush:run'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
