[build-system]
requires = [
    "aniso8601==9.0.1",
    "beautifulsoup4==4.9.3",
    "boto3==1.18.31",
    "botocore==1.21.31",
    "certifi==2021.5.30",
    "charset-normalizer==2.0.4",
    "click==8.0.1",
    "colorama==0.4.4",
    "Flask==2.0.1",
    "Flask-RESTful==0.3.9",
    "idna==3.2",
    "itsdangerous==2.0.1",
    "Jinja2==3.0.1",
    "jmespath==0.10.0",
    "MarkupSafe==2.0.1",
    "python-dateutil==2.8.2",
    "pytz==2021.1",
    "requests==2.26.0",
    "s3transfer==0.5.0",
    "six==1.16.0",
    "soupsieve==2.2.1",
    "urllib3==1.26.6",
    "Werkzeug==2.0.1",
    "setuptools>=42",
    "wheel",
]
build-backend = "setuptools.build_meta"
