[tool.poetry]
authors = ["abersheeran <me@abersheeran.com>"]
description = ""
license = "Apache-2.0"
name = "indexpy-auth"
readme = "README.md"
version = "0.1.0"

homepage = "https://github.com/index-py/indexpy-auth"
repository = "https://github.com/index-py/indexpy-auth"

classifiers = [
  "Programming Language :: Python :: 3",
]

packages = [
  {include = "indexpy_auth"},
]

[tool.poetry.dependencies]
python = "^3.7"

"index.py" = "^0.19.0"

[tool.poetry.dev-dependencies]
black = {version = "*", allow-prereleases = true}
isort = "*"

flake8 = "*"
mypy = "^0.910"

pytest = "^5.4.3"

[tool.isort]
profile = "black"

[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]
