[tool.poetry]
name = "canopy-network"
version = "0.0.52"
description = "A decentralized social network of personal websites"
authors = ["Angelo Gladding <angelo@lahacker.net>"]
license = "AGPL-3.0-or-later"
readme = "README.md"
packages = [
    { include = "canopy" }
]
repository = "https://understory.cloud/canopy.git"

[tool.poetry.urls]
Homepage = "https://canopy.stream"
Issues = "https://github.com/canopy/canopy/issues"

[tool.poetry.plugins."web.apps"]
canopy = "canopy:app"

[tool.poetry.dependencies]
python = "^3.9,<3.10"
understory = "^0.0.63"
# understory = {path = "../understory"}

[tool.poetry.dev-dependencies]
ipython = "^7.25.0"
pytest = "^6.2.4"
pytest-cov = "^2.12.1"
black = "^21.6b0"
isort = "^5.9.2"
flake8 = "^3.9.2"
flake8-docstrings = "^1.6.0"
pep8-naming = "^0.12.0"
webdriver-manager = "^3.4.2"
pytest-gevent = "^1.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
