[build-system]
requires = ["setuptools", "wheel"]

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
combine_as_imports = true

[tool.pytest.ini_options]
addopts = "--mpl"

[tool.mypy]
python_version = "3.9"
