
# This file was generated by 'versioneer.py' (0.16+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "e366e693f0280f0566b4e50fb36d4854c7d96116",
 "version": "3.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
