
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-31T09:24:44+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "5ca086eafa88f4523b2c19efd5eb703589f69294",
 "version": "0.4,6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
