
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-02T16:37:07-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "484992c7132d513102034b3164ef751efb9a937e",
 "version": "0.8.332"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
