# To validate the contents of your configuration file
# run the following command in the folder where the configuration file is located:
# codacy-analysis-cli validate-configuration --directory `pwd`
# To analyse, run:
# codacy-analysis-cli analyse --tool remark-lint --directory `pwd`
---
engines:
  pylintpython3:
    exclude_paths:
      - config/engines.yml
  remark-lint:
    exclude_paths:
      - config/engines.yml
exclude_paths:
  - 'tests/**'
