
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-31T09:46:58+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c0ed02ae48f865029ee114944515ba7c4aa8b90f",
 "version": "0.4.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
