# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/api_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="services/api_service.proto",
    package="aether",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x1aservices/api_service.proto\x12\x06\x61\x65ther"\x14\n\x12HealthCheckRequest"|\n\x13HealthCheckResponse\x12\x32\n\x06status\x18\x01 \x01(\x0e\x32".aether.HealthCheckResponse.Status"1\n\x06Status\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07HEALTHY\x10\x01\x12\r\n\tUNHEALTHY\x10\x02\x32\xa3\x01\n\nAPIService\x12\x46\n\x0bHealthCheck\x12\x1a.aether.HealthCheckRequest\x1a\x1b.aether.HealthCheckResponse\x12M\n\x10HealthCheckWatch\x12\x1a.aether.HealthCheckRequest\x1a\x1b.aether.HealthCheckResponse0\x01\x62\x06proto3',
)


_HEALTHCHECKRESPONSE_STATUS = _descriptor.EnumDescriptor(
    name="Status",
    full_name="aether.HealthCheckResponse.Status",
    filename=None,
    file=DESCRIPTOR,
    create_key=_descriptor._internal_create_key,
    values=[
        _descriptor.EnumValueDescriptor(
            name="UNKNOWN",
            index=0,
            number=0,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="HEALTHY",
            index=1,
            number=1,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="UNHEALTHY",
            index=2,
            number=2,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=135,
    serialized_end=184,
)
_sym_db.RegisterEnumDescriptor(_HEALTHCHECKRESPONSE_STATUS)


_HEALTHCHECKREQUEST = _descriptor.Descriptor(
    name="HealthCheckRequest",
    full_name="aether.HealthCheckRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=38,
    serialized_end=58,
)


_HEALTHCHECKRESPONSE = _descriptor.Descriptor(
    name="HealthCheckResponse",
    full_name="aether.HealthCheckResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="status",
            full_name="aether.HealthCheckResponse.status",
            index=0,
            number=1,
            type=14,
            cpp_type=8,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[
        _HEALTHCHECKRESPONSE_STATUS,
    ],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=60,
    serialized_end=184,
)

_HEALTHCHECKRESPONSE.fields_by_name["status"].enum_type = _HEALTHCHECKRESPONSE_STATUS
_HEALTHCHECKRESPONSE_STATUS.containing_type = _HEALTHCHECKRESPONSE
DESCRIPTOR.message_types_by_name["HealthCheckRequest"] = _HEALTHCHECKREQUEST
DESCRIPTOR.message_types_by_name["HealthCheckResponse"] = _HEALTHCHECKRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HealthCheckRequest = _reflection.GeneratedProtocolMessageType(
    "HealthCheckRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _HEALTHCHECKREQUEST,
        "__module__": "services.api_service_pb2"
        # @@protoc_insertion_point(class_scope:aether.HealthCheckRequest)
    },
)
_sym_db.RegisterMessage(HealthCheckRequest)

HealthCheckResponse = _reflection.GeneratedProtocolMessageType(
    "HealthCheckResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _HEALTHCHECKRESPONSE,
        "__module__": "services.api_service_pb2"
        # @@protoc_insertion_point(class_scope:aether.HealthCheckResponse)
    },
)
_sym_db.RegisterMessage(HealthCheckResponse)


_APISERVICE = _descriptor.ServiceDescriptor(
    name="APIService",
    full_name="aether.APIService",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=187,
    serialized_end=350,
    methods=[
        _descriptor.MethodDescriptor(
            name="HealthCheck",
            full_name="aether.APIService.HealthCheck",
            index=0,
            containing_service=None,
            input_type=_HEALTHCHECKREQUEST,
            output_type=_HEALTHCHECKRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="HealthCheckWatch",
            full_name="aether.APIService.HealthCheckWatch",
            index=1,
            containing_service=None,
            input_type=_HEALTHCHECKREQUEST,
            output_type=_HEALTHCHECKRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_APISERVICE)

DESCRIPTOR.services_by_name["APIService"] = _APISERVICE

# @@protoc_insertion_point(module_scope)
