#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['lambdex', 'lambdex.bin', 'lambdex.resources']

package_data = \
{'': ['*']}

install_requires = \
['pex>=1.1.15']

extras_require = \
{"test-gcp-http:python_version < '3.6'": ['flask<2'],
 "test-gcp-http:python_version >= '3.6'": ['flask~=2.0.0']}

entry_points = \
{'console_scripts': ['lambdex = lambdex.bin.lambdex:main']}

setup(name='lambdex',
      version='0.1.6',
      description='Lambdex turns pex files into aws lambda python functions.',
      author='The Lambdex developers',
      author_email='pantsbuild@gmail.com',
      url='https://github.com/pantsbuild/lambdex',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      entry_points=entry_points,
      python_requires='>=2.7,<3.10,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*,!=3.5.*',
     )
