TEAM_MAPPER = {
    ('Leeds United', 'Leeds', '利兹联', '利兹'): 'Leeds United',
    ('Real Madrid', '皇马'): 'Real Madrid',
    ('Liverpool', '利物浦'): 'Liverpool',
    ('Bayern', '拜仁'): 'Bayern Munich',
    ('Chelsea', '切尔西'): 'Chelsea',
    ('Man Utd', '曼联', 'Manchester United', 'Man U'): 'Manchester United',
    ('Man City', '曼城', 'Manchester City'): 'Manchester City',
    ('Barcelona', '巴萨', '巴塞罗那', 'Barc'): 'Barcelona',
    ('Paris', 'Paris SG', 'PSG', '巴黎'): 'Paris SG',
    ('Inter', '国米', '国际', 'Inter Milan'): 'Inter',
    ('Napoli', '那不勒斯'): 'Napoli',
    ('Lazio', '拉齐奥'): 'Lazio',
    ('Atletico Madrid', '马竞'): 'Atletico Madrid',
    ('Sevilla', '塞维利亚'): 'Sevilla',
    ('Leichester', '莱切斯特', 'Leicester'): 'Leichester',
    ('Juventus', '尤文', '尤文图斯'): 'Juventus',
    ('Atalanta', '亚特兰大'): 'Atalanta',
    ('RB Leipzig', '莱比锡', 'LPZ'): 'RB Leipzig',
    ('Tottenham', '托特纳姆', '热刺', 'Tottenam'): 'Tottenham',
    ('AC Milan', 'AC米兰', 'Milan'): 'AC Milan',
    ('Dortmund', '多特蒙德'): 'Dortmund',
    ('Arsenal', '阿森纳'): 'Arsenal',
    ('Everton', '埃弗顿'): 'Everton',
    ('Villarreal', '比利亚雷亚尔'): 'Villarreal',
    ('Getafe', '赫塔费'): 'Getafe',
    ('Newcastle', '纽卡斯尔'): 'Newcastle',
    ('Wolverhampton', '狼'): 'Wolverhampton',
    ('Southampton', '南安普顿'): 'Southampton',
    ('Espanyol', '西班牙人'): 'Espanyol',
    ('Valencia', '瓦伦西亚'): 'Valencia',
    ('Shakhtar Donetsk', '矿工'): 'Shakhtar Donetsk',
    ('Shanghai Shenhua', '申花'): 'Shanghai Shenhua'
}
