#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['recipely']

package_data = \
{'': ['*']}

install_requires = \
['flit_core>=2.2.0',
 'coloredlogs',
 'python-frontmatter',
 'jinja2',
 'setuptools_scm',
 'python-slugify',
 'jinja_markdown']

entry_points = \
{'console_scripts': ['recipely = recipely:main']}

setup(name='recipely',
      version='0.0.post845',
      description='Initialisation module for recipely.',
      author='Martyn van Dijke',
      author_email='martijnvdijke600@gmail.com',
      url='https://github.com/martynvdijke/recipely',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      entry_points=entry_points,
     )
