
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-31T22:18:30+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "219c16e82de2746f959b8e7830df2ff0d8c47a52",
 "version": "0.5.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
