
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-01T09:13:47+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d5093812200bd18c1ffe29741faedec305085f4f",
 "version": "2529"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
