
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-02T14:06:26+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "4277bd739b5c345faec5b23fa421f6355f8e7f78",
 "version": "0.4.38"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
