name: Pull Request
on:
  pull_request:
    branches:
      - master

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          - lint_jsonnet
          - lint_yaml
          - lint_adoc
    steps:
      - uses: actions/checkout@v2
      - name: Run {% raw %}${{ matrix.command }}{% endraw %}
        run: make {% raw %}${{ matrix.command }}{% endraw %}
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: snow-actions/eclint@v1.0.1
        with:
          args: 'check'
