# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from jgreenepack.configuration import Configuration


class HostRegistrationResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'next_step_runner_command': 'object'
    }

    attribute_map = {
        'next_step_runner_command': 'next_step_runner_command'
    }

    def __init__(self, next_step_runner_command=None, _configuration=None):  # noqa: E501
        """HostRegistrationResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._next_step_runner_command = None
        self.discriminator = None

        if next_step_runner_command is not None:
            self.next_step_runner_command = next_step_runner_command

    @property
    def next_step_runner_command(self):
        """Gets the next_step_runner_command of this HostRegistrationResponse.  # noqa: E501

        Command for starting the next step runner  # noqa: E501

        :return: The next_step_runner_command of this HostRegistrationResponse.  # noqa: E501
        :rtype: object
        """
        return self._next_step_runner_command

    @next_step_runner_command.setter
    def next_step_runner_command(self, next_step_runner_command):
        """Sets the next_step_runner_command of this HostRegistrationResponse.

        Command for starting the next step runner  # noqa: E501

        :param next_step_runner_command: The next_step_runner_command of this HostRegistrationResponse.  # noqa: E501
        :type: object
        """

        self._next_step_runner_command = next_step_runner_command

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HostRegistrationResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HostRegistrationResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, HostRegistrationResponse):
            return True

        return self.to_dict() != other.to_dict()
