
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-29T19:15:26-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "1b9c1a6e1822a3eba72360ef57e7006e0ea65477",
 "version": "0.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
