from typing import Any

class TerseExecutableError(Exception):
    value: Any = ...
    def __init__(self, value: str) -> None: ...

class TerseExecutableParser:
    def __init__(self, image_path: str) -> None: ...
    @property
    def signature(self) -> str: ...
    @property
    def machine(self) -> int: ...
    @property
    def number_of_sections(self) -> int: ...
    @property
    def subsystem(self) -> int: ...
    @property
    def stripped_size(self) -> int: ...
    @property
    def address_of_entry_point(self) -> int: ...
    @property
    def base_of_code(self) -> int: ...
    @property
    def image_base(self) -> int: ...
