[build-system]
requires = ["setuptools>=41.0", "setuptools-scm", "wheel"]
build-backend = "setuptools.build_meta"


[tool]


[tool.black]
max_line_length = 99
quiet = true


[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 99
quiet = true


[tool.pylint.messages_control]
disable = "E1120, R0914, E0401, R0912, R0916, R0913, W0104"
