
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-31T10:30:45+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "3ffd1efd97a005d7861a2f34fb870585e0988fc1",
 "version": "0.4.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
