[package]
name = "python-calamine"
version = "0.0.2"
authors = ["Dmitriy <dimastbk@yandex.ru>"]
description = "Python binding for Rust's library for reading excel and odf file - calamine"
edition = "2018"
homepage = "https://github.com/dimastbk/python-calamine"
license = "MIT"
readme = "README.md"
repository = "https://github.com/dimastbk/python-calamine"

[lib]
name = "python_calamine"
crate-type = ["cdylib"]

[dependencies]
calamine = "0.18.0"
pyo3 = {version = "0.14.3", features = ["extension-module"] }
