# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import jgreenepack
from jgreenepack.models.step_type import StepType  # noqa: E501
from jgreenepack.rest import ApiException


class TestStepType(unittest.TestCase):
    """StepType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStepType(self):
        """Test StepType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = jgreenepack.models.step_type.StepType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
