[tool.poetry]
name = "cleanup-dungeondraft-asset-packs"
version = "0.1.1"
description = "CLI tool to clean up Dungeondraft asset packs"
authors = ["Balthazar Rouberol <br@imap.cc>"]
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3 :: Only",
]
readme = "README.md"
repository = "https://github.com/brouberol/cleanup-dungeondraft-asset-packs"
keywords = [
    "Dungeondraft"
]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
cleanup-dungeondraft-asset-packs = 'cleanup_dungeondraft_asset_packs:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
