
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-01T14:17:05-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "f4dd1da13f9d6bdc0daef6ea59e57f3be7012079",
 "version": "v0.0.1a"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
