# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/itemtype/rpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ivi_sdk.api.itemtype import definition_pb2 as api_dot_itemtype_dot_definition__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='api/itemtype/rpc.proto',
  package='ivi.rpc.api.itemtype',
  syntax='proto3',
  serialized_options=b'\n)games.mythical.ivi.sdk.proto.api.itemtypeP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16\x61pi/itemtype/rpc.proto\x12\x14ivi.rpc.api.itemtype\x1a\x1d\x61pi/itemtype/definition.proto\x1a\x1bgoogle/protobuf/empty.proto2\xc4\x03\n\x0fItemTypeService\x12p\n\x0e\x43reateItemType\x12-.ivi.proto.api.itemtype.CreateItemTypeRequest\x1a/.ivi.proto.api.itemtype.CreateItemAsyncResponse\x12^\n\x0cGetItemTypes\x12+.ivi.proto.api.itemtype.GetItemTypesRequest\x1a!.ivi.proto.api.itemtype.ItemTypes\x12t\n\x0e\x46reezeItemType\x12-.ivi.proto.api.itemtype.FreezeItemTypeRequest\x1a\x33.ivi.proto.api.itemtype.FreezeItemTypeAsyncResponse\x12i\n\x16UpdateItemTypeMetadata\x12\x35.ivi.proto.api.itemtype.UpdateItemTypeMetadataPayload\x1a\x16.google.protobuf.Empty\"\x00\x42-\n)games.mythical.ivi.sdk.proto.api.itemtypeP\x01\x62\x06proto3'
  ,
  dependencies=[api_dot_itemtype_dot_definition__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_ITEMTYPESERVICE = _descriptor.ServiceDescriptor(
  name='ItemTypeService',
  full_name='ivi.rpc.api.itemtype.ItemTypeService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=109,
  serialized_end=561,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateItemType',
    full_name='ivi.rpc.api.itemtype.ItemTypeService.CreateItemType',
    index=0,
    containing_service=None,
    input_type=api_dot_itemtype_dot_definition__pb2._CREATEITEMTYPEREQUEST,
    output_type=api_dot_itemtype_dot_definition__pb2._CREATEITEMASYNCRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetItemTypes',
    full_name='ivi.rpc.api.itemtype.ItemTypeService.GetItemTypes',
    index=1,
    containing_service=None,
    input_type=api_dot_itemtype_dot_definition__pb2._GETITEMTYPESREQUEST,
    output_type=api_dot_itemtype_dot_definition__pb2._ITEMTYPES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='FreezeItemType',
    full_name='ivi.rpc.api.itemtype.ItemTypeService.FreezeItemType',
    index=2,
    containing_service=None,
    input_type=api_dot_itemtype_dot_definition__pb2._FREEZEITEMTYPEREQUEST,
    output_type=api_dot_itemtype_dot_definition__pb2._FREEZEITEMTYPEASYNCRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateItemTypeMetadata',
    full_name='ivi.rpc.api.itemtype.ItemTypeService.UpdateItemTypeMetadata',
    index=3,
    containing_service=None,
    input_type=api_dot_itemtype_dot_definition__pb2._UPDATEITEMTYPEMETADATAPAYLOAD,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ITEMTYPESERVICE)

DESCRIPTOR.services_by_name['ItemTypeService'] = _ITEMTYPESERVICE

# @@protoc_insertion_point(module_scope)
