# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/player/definition.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common/player/definition.proto',
  package='ivi.proto.common.player',
  syntax='proto3',
  serialized_options=b'\n*games.mythical.ivi.sdk.proto.common.playerP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1e\x63ommon/player/definition.proto\x12\x17ivi.proto.common.player*9\n\x0bPlayerState\x12\x12\n\x0ePENDING_LINKED\x10\x00\x12\n\n\x06LINKED\x10\x01\x12\n\n\x06\x46\x41ILED\x10\x02\x42.\n*games.mythical.ivi.sdk.proto.common.playerP\x01\x62\x06proto3'
)

_PLAYERSTATE = _descriptor.EnumDescriptor(
  name='PlayerState',
  full_name='ivi.proto.common.player.PlayerState',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PENDING_LINKED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LINKED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=59,
  serialized_end=116,
)
_sym_db.RegisterEnumDescriptor(_PLAYERSTATE)

PlayerState = enum_type_wrapper.EnumTypeWrapper(_PLAYERSTATE)
PENDING_LINKED = 0
LINKED = 1
FAILED = 2


DESCRIPTOR.enum_types_by_name['PlayerState'] = _PLAYERSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
