[tool.poetry]
name = "erroi"
version = "0.1.0"
description = "ERRant Other Improver"
authors = ["Aneta Melisa Stal <melisa-qordoba@writer.com>"]

[tool.poetry.dependencies]
python = "^3.8"
SoundsLike = "^0.0.11"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
