
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-30T14:35:33+0000",
 "dirty": true,
 "error": null,
 "full-revisionid": "59f4039b3f4c64089ef13b0274dfcad4e7fcd123",
 "version": "9.1.1.post0.dev3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
