
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-31T14:29:40+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "8b6bd2705fdb4102f736f3c0fb9bfa0c54c835d6",
 "version": "0.4.27"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
