
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-31T00:38:09+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "97aa49773338caece9ec5bd8bfd0cd2af90e03ad",
 "version": "0.3.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
