
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-31T11:56:00+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d420d5c54101702eaa90ceb863bab6b22addd160",
 "version": "0.4.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
