
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-28T12:45:09-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "22c0877b71a0318f02c43468a4194f052ea6df45",
 "version": "13.4.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
