
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-03T13:04:46-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "a3382189b5a0f353ed20576b4dd0c0eb66916c27",
 "version": "5.1.7.4-alpha2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
