[build-system]
requires = [ "poetry>=0.12",]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "pipen"
version = "0.0.4"
description = "A pipeline framework for python"
authors = [ "pwwang <pwwang@pwwang.com>",]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/pwwang/pipen"
repository = "https://github.com/pwwang/pipen"

[tool.poetry.dependencies]
python = "^3.7.1" # align with datar/pandas
toml = "^0.10"
varname = "*"
liquidpy = "^0.6"
diot = "*"
pyparam = "*"
xqute = "*"
python-simpleconf = "*"
pandas = "1.*"
uvloop = "0.*"
rich = "10.*"
python-slugify = "4.*"
simplug = "*"
enlighten = "1.*"
cached-property = "1.*"
more-itertools = "8.*"
pipda = "*"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-cov = "*"
jinja2 = "^2.0.0"
datar = "*"

[tool.poetry.scripts]
pipen = "pipen.cli:main"
