__title__ = "rivet"
__description__ = "A Python-to-S3 interface with added convenience features."
__url__ = "https://github.com/neighborhoods/rivet"
__version__ = "1.6.0"
__author__ = "George Wood (@Geoiv)"
__author_email__ = "george.wood@55places.com"
