#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['aracnid_logger']

package_data = \
{'': ['*']}

install_requires = \
['slack-bolt']

setup(name='aracnid_logger',
      version='1.0.0a5',
      description='A simple customization of the Python Logging System.',
      author='Jason Romano',
      author_email='aracnid@gmail.com',
      url='https://github.com/lakeannebrewhouse/aracnid-logger',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      python_requires='~=3.8',
     )
