[tool.poetry]
name = "necstdb"
version = "0.2.5"
description = "Database for NECST."
authors = ["Kaoru Nishikawa <k.nishikawa@a.phys.nagoya-u.ac.jp>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/ogawa-ros/necstdb"
repository = "https://github.com/ogawa-ros/necstdb"

[tool.poetry.dependencies]
python = "^3.6.1"
numpy = "^1.19.0"
pandas = "^1.1.0"

[tool.poetry.dev-dependencies]
pytest = "^6.1.0"
black = "^20.8b"
flake8 = "^3.8.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
