[tool.poetry]
name = "omniblack.model"
version = "0.1.17"
description = "A library enabling model driven development."
authors = ["Terry Patterson <Terryp@wegrok.net>"]
license = "AGPL-3.0-or-later"
include = [
    'omniblack/model/structs/*.json',
    'omniblack/model/structs/__init__.py',
]
packages = [
    {include = 'omniblack'},
]

[tool.poetry.dependencies]
python = "^3.9"
rx = "^3.1.1"
"ruamel.yaml" = {version="^0.16.12", optional = true}
anyio = "^3.0.0"
sniffio = "^1.2.0"
more_itertools = "^8.7.0"
humanize = "^3.4.1"
toml = {version = "^0.10.2", optional = true}
atpublic = "^2.3"

[tool.poetry.extras]
toml = ['toml']
yaml = ['ruamel.yaml']

[tool.poetry.dev-dependencies]
bpython = "^0.21"
pytest = "^6.2.3"
flake8 = "^3.9.1"
bandit = "^1.7.0"
isort = "^5.8.0"

[tool.isort]
group_by_package = true
remove_redundant_aliases = true
combine_straight_imports = true
multi_line_output = 3
include_trailing_comma = true
combine_as_imports = true
combine_star = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
