from RewardsBot import browserSetup
from RewardsBot import generateDailyReport
from RewardsBot import login
from RewardsBot import completeDailySet
from RewardsBot import checkifdailypromotionexist
from RewardsBot import reportDailySet
from RewardsBot import completePunchCards
from RewardsBot import completeMorePromotions
from RewardsBot import checkifmorepromotionexist
from RewardsBot import getRemainingSearches
from RewardsBot import bingSearches
from RewardsBot import reportSearchSet
from RewardsBot import reportDeparture
from RewardsBot import Get_point_total
from RewardsBot import reportSearchSet 
from RewardsBot import reportPromotionsSet 
