
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-28T18:46:54+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "aa602a34941efea8ca33d65b8f54dc225fa2ced5",
 "version": "0.0.58"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
