
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-31T10:48:43+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "57de9bb2a966a901a4cad703a24ed9c831abf0f9",
 "version": "0.4.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
