[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 120

[tool.isort]
known_first_party = ["endo_datastructures"]

# required for compatibility with black:
profile = "black"

# To maintain consistency with other settings
line_length = 120

[tool.pytest.ini_options]

testpaths = "test"

addopts = [
    "--verbose",
    "--cov=route53_ddns",
    "--cov-report=term-missing",
    "--cov-report=html:coverage_html",
    "--cov-report=xml:coverage.xml",
    "--color=yes",
    "--cov-fail-under=100"
]
