[build-system]
requires = [
    "numpy==1.19.5",
    "matplotlib==3.4.2",
    "pandas==1.2.4",
    "requests==2.25.1",
    "selenium==3.141.0",
    "scipy==1.6.3",
    "yellowbrick==1.3.post1",
    "statsmodels==0.12.2",
    "scikit-learn==0.24.2",
    "flit_core >=3.2,<4",
    "setuptools>=42",
    "wheel"
    ]

# build-backend = "flit_core.buildapi"
build-backend = "setuptools.build_meta"

[project]
name = "warzone analysis"
authors = [{name = "Peter Rigali", email = "peterjrigali@gmail.com"}]
dynamic = ["2.3.0", "A module for analysis of Call of Duty Warzone matches."]