[tool.poetry]
name = "fileSharing"
version = "0.1.0"
description = ""
authors = ["YCipriani <yonatancipriani@outlook.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Flask = "^2.0.1"
Flask-RESTful = "^0.3.9"
colorlog = "^5.0.1"
requests = "^2.26.0"
pymongo = "^3.12.0"
dnspython = "^2.1.0"
black = "^21.7b0"
pip = "^21.2.4"
pyinstaller = "^4.5.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
