apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{cookiecutter.project_name}}-db
spec:
  selector:
    matchLabels:
      app: {{cookiecutter.project_name}}-db
  template:
    metadata:
      labels:
        app: {{cookiecutter.project_name}}-db
    spec:
      containers:
        - name: database
          image: {{cookiecutter.db_info.image}}
          resources:
            limits:
              memory: "300Mi"
              cpu: "200m"
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: "{{cookiecutter.project_name}}-db"
spec:
  selector:
    app: {{cookiecutter.project_name}}-db
  ports:
    - port: {{cookiecutter.db_info.port}}
      targetPort: {{cookiecutter.db_info.port}}
