
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-29T02:12:07+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "fc69e1d96c6250c6479ea7575b9e6f73e70b8baf",
 "version": "0.7.dev2135"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
