
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-03T21:54:37+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e78fbeb0a381b3ca4a44c7b24603d9a0ff4d943b",
 "version": "0.27.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
