[tool.poetry]
name = "PIOntologyExtractor"
version = "0.1.0"
description = "A package that can deal with extracting useful info from our Graph Ontology."
authors = ["David Berenstien <david.berenstein@pandoraintelligence.com>"]
license = "Pandora Intelligence"

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.3.2"
piauthorizer = "^0.9.5"
jaal = "^0.0.9"
openpyxl = "^3.0.7"

[tool.poetry.dev-dependencies]
black = {version = "^21.7b0", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
