# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import jgreenepack
from jgreenepack.models.list_manifests import ListManifests  # noqa: E501
from jgreenepack.rest import ApiException


class TestListManifests(unittest.TestCase):
    """ListManifests unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListManifests(self):
        """Test ListManifests"""
        # FIXME: construct object with mandatory attributes with example values
        # model = jgreenepack.models.list_manifests.ListManifests()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
