
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "4f1087ee44c9f57a3cfb515f0cdbe2a5c892dd3e",
 "version": "1.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
