[tool.poetry]
name = "eospyo"
version = "0.2.0"
description = "Interact with EOSIO blockchain networks"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
