
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-31T13:09:40+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "cfe940e4cf4ff20878e45989e45df13622a88cec",
 "version": "0.4.23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
