[tool.poetry]
name = "revdb"
version = "1.1.4"
description = ""
authors = ["Chien <a0186163@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.7,<4.0"
mongoengine = "^0.23.0"
dnspython = "^2.1.0"
requests = "^2.25.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.3"
pytest-cov = "^2.11.1"
mypy = "^0.812"
black = "^20.8b1"
isort = "^5.8.0"
autoflake = "^1.4"
flake8 = "^3.9.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"