[tool.poetry]
name = "sphinx-needs-capri"

# Don't miss updates in conf.py and changelog.rst
version = "0.1.0"

description = "Synchronize codebeamer with Sphinx-Needs"
authors = ["team useblocks <info@useblocks.com>"]
license = "BSL 1.1"
readme = "README.rst"
repository = "http://github.com/useblocks/sphinx-needs-capri"
documentation = "https://sphinx-needs-capri.readthedocs.io/en/latest/"
classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        "License :: Other/Proprietary License",
        'Operating System :: OS Independent',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Topic :: Documentation',
        'Topic :: Utilities',
        'Framework :: Sphinx :: Extension',
    ]

packages = [
    {include = "sphinxcontrib", from = "."}
]

[tool.poetry.dependencies]
python = "^3.6"
sphinxcontrib-needs = "^0.7"
sphinx-needs-extensions = "^0.1.0"

[tool.poetry.dev-dependencies]

# test dependencies
nose = "^1.3.7"
sphinx-testing = ">=1.0"

# lint dependences
flake8 = "^3.9.0"
pep8-naming = "^0.11.1"

# formatting dependencies
black = "^20.8b1"
isort = "^5.7.0"
flake8-isort = "^4.0.0"
flake8-black = "^0.2.1"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"

[tool.poetry.extras]
docs = ["sphinx>=4.0"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

