
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-01T16:41:53-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "8c49e44da85908b3e2594a60f9961a1ce87ddbe2",
 "version": "1.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
