[tool.poetry]
name = "sphinx-needs-extensions"
version = "0.1.0"
description = "Core package to provide core functionalities to all Sphinx-Needs extensions"
authors = ["team useblocks"]
license = "BUSL-1.1"

[tool.poetry.dependencies]
python = "^3.6"
sphinxcontrib-needs = "^0.7"

[tool.poetry.dev-dependencies]

# test dependencies
nose = "^1.3.7"
sphinx-testing = ">=1.0"

# lint dependences
flake8 = "^3.9.0"
pep8-naming = "^0.11.1"

# formatting dependencies
black = "^20.8b1"
isort = "^5.7.0"
flake8-isort = "^4.0.0"
flake8-black = "^0.2.1"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"

[tool.poetry.extras]
docs = ["sphinx>=4.0"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
