
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-05T10:01:53-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "566d5307693740273c9c98ea96c2751a9631ff7c",
 "version": "v0.2.23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
