
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-31T15:36:40-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "0948cb337f90832f02d0a1451d80f7e68b66c860",
 "version": "4.7.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
