[tool.poetry]
name = "darbiadev-shipping"
version = "0.4.0"
description = "darbiadev-shipping"
authors = ["Bradley Reynolds <bradley.reynolds@darbia.dev>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/darbiadev/darbiadev-shipping"
documentation = "https://darbiadev.github.io/darbiadev-shipping/"

[tool.poetry.dependencies]
# Python
python = "^3.9"

darbiadev-ups = { version = "^0.5.0", optional = true }
darbiadev-fedex = { version = "^0.3.0", optional = true }
darbiadev-usps = { version = "^0.5.0", optional = true }

# Docs
sphinx = { version = "^4.1.1", optional = true }
sphinxcontrib-napoleon = { version =  "^0.7", optional = true }
sphinxcontrib-autoprogram = { version = "^0.1.7", optional = true }
sphinx-rtd-theme = { version = "^0.5.2", optional = true }
toml = { version = "^0.10.2", optional = true }

# Tests
pytest = { version = "^6.2.4", optional = true }
tox = { version = "^3.24.0", optional = true }

[tool.poetry.extras]
ups = ["darbiadev-ups"]
fedex = ["darbiadev-fedex"]
usps = ["darbiadev-usps"]

docs = ["sphinx", "sphinxcontrib-napoleon", "sphinxcontrib-autoprogram", "sphinx_rtd_theme", "toml"]
tests = ["pytest", "tox"]

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.sphinx]
copyright = "2021, Darbia"
author = "Bradley Reynolds"
api_dir = "darbiadev_shipping"

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py39
isolated_build = True
[testenv]
deps =
    pytest
commands =
    pytest
"""
