
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-30T23:21:51+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "513d498d7a2ea7fd74517c0a3fef22c344ff07b3",
 "version": "0.2.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
