# -*- coding: utf-8 -*-

"""
cookiesapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from cookiesapi.models.brand_spec import BrandSpec


class BrandList(object):

    """Implementation of the 'BrandList' model.

    Specifies a list of resulting Brand records.

    Attributes:
        brand (list of BrandSpec): Array of resulting brand records.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "brand": 'brand'
    }

    def __init__(self,
                 brand=None):
        """Constructor for the BrandList class"""

        # Initialize members of the class
        self.brand = brand

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        brand = None
        if dictionary.get('brand') is not None:
            brand = [BrandSpec.from_dictionary(x) for x in dictionary.get('brand')]

        # Return an object of this model
        return cls(brand)
