
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-01T11:10:11+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "90a505b1597eb2e99adfbc0f88edd8e112095b97",
 "version": "0.7.0.post.dev416"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
