# -*- coding: utf-8 -*-

"""
cookiesapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CustomQueryAuth:

    @staticmethod
    def apply(config, http_request):
        """ Add custom authentication to the request.

        Args:
            config (Configuration): The Configuration object which holds the
                authentication information.
            http_request (HttpRequest): The HttpRequest object to which
                authentication will be added.

        """
        http_request.add_query_parameter("apikey", config.apikey)
