
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-20T14:49:52+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d0b9a4971e3bae98453975d46b0b3062d042f57d",
 "version": "v11.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
