
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-30T16:58:24+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "831c86f28e9cb109acee26ce69481b86da33a775",
 "version": "1.11.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
