
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-02T15:29:34+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "bbfa84e76d98fd04cea6bf4a519feee94d4082fd",
 "version": "v0.10.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
