[tool.poetry]
name = "imgmeta"
version = "0.1.1"
description = ""
authors = ["Bao Hengtao <baohengtao@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.9"
geopy = "^2.2.0"
pymongo = "^3.12.0"
loguru = "^0.5.3"
photoscript = "^0.1.4"
osxphotos = "^0.42.80"
sinaspider = "^0.3.2"
click = "^8.0.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
jupyterlab = "*"
JLDracula = "*"
jupyterlab_vim = "*"
ptpython = "*"
jupyterlab-lsp = "*"
python-lsp-server = "^1.2.1"
Sphinx = "^4.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
