[tool.poetry]
name = "requests-ratelimiter"
version = "0.2.0"
description = "Rate-limiting for the requests library"
authors = ["Jordan Cook"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/JWCook/requests-ratelimiter"
repository = "https://github.com/JWCook/requests-ratelimiter"
documentation = "https://requests-ratelimiter.readthedocs.io"
keywords = ["requests", "rate-limiting", "leaky-bucket"]

[tool.poetry.dependencies]
python = "^3.6.2"
pyrate-limiter = "^2.3"
requests = "^2.20"

# Documentation dependencies needed for Readthedocs builds
furo = {version = "2021.8.17b43", optional = true}
myst-parser = {version = "^0.15.1", optional = true}
sphinx = { version = "^4.0.2", optional = true }
sphinx-autodoc-typehints = { version = "^1.11", optional = true }
sphinx-copybutton = { version = ">=0.3,<0.5", optional = true }

[tool.poetry.extras]
docs = ["furo", "myst-parser", "sphinx", "sphinx-autodoc-typehints",
        "sphinx-copybutton", "sphinxcontrib-apidoc"]

[tool.poetry.dev-dependencies]
pre-commit = "^2.12"
pytest = "^6.2"
pytest-cov = ">=2.11"
pytest-xdist = ">=2.2"
requests-mock = "^1.8"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
skip-string-normalization = true

[tool.coverage.html]
directory = 'test-reports'

[tool.isort]
profile = 'black'
line_length = 100
skip_gitignore = true
known_first_party = ['tests']

[tool.mypy]
ignore_missing_imports = true
