
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-29T16:44:29-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "6b539826fef0babbbf2884004f4c1497d6cd357d",
 "version": "13.4.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
