[tool.poetry]
name = "nbox"
version = "0.1.4"
description = "Makes using a host of opensource deep learning algorithms easier"
authors = [
            "Yash Bonde <bonde.yash97@gmail.com>",
            "Aakash Kaushik <kaushikaakash7539@gmail.com>",
            "NBX Research <research@nimblebox.ai>"
          ]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = [
  "poetry-core>=1.0.0",
  "randomname==0.1.3",
  "rich==10.7.0"
]
build-backend = "poetry.core.masonry.api"
