[tool.poetry]
name = "newscatcherapi"
version = "0.1.0"
description = "Python SDK NewsCatcher News API"
authors = ["Maksym Sugonyaka <maksym@newscatcherapi.com>"]

[tool.poetry.dependencies]
python = "*"
pendulum = "^1.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
requests="^2.24.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
