
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-30T15:51:40-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "a0da31ed67609f0b7e4bfaa468850515aabb094b",
 "version": "11.13.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
