VERSION_YEAR = 2021
VERSION_MONTH = int('09')
VERSION_DAY = int('02')
VERSION_HOUR = int('15')
VERSION_MINUTE = int('31')
MAJOR_VERSION = 0
MINOR_VERSION = 4
PATCH_VERSION = 202109021531
version_date = '2021/09/02 15:31'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
