VERSION_YEAR = 2021
VERSION_MONTH = int('09')
VERSION_DAY = int('04')
VERSION_HOUR = int('05')
VERSION_MINUTE = int('54')
MAJOR_VERSION = 0
MINOR_VERSION = 4
PATCH_VERSION = 202109040554
version_date = '2021/09/04 05:54'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
