[tool]
[tool.poetry]
name = "asyncgram"
version = "0.0.2"
description = "A lightweight, asynchronous telegram logging client"
authors = ["sumermalhotra"]
readme = "README.md"

[tool.poetry.dependencies]
python = "==3.7"
python-dotenv = "*"
requests = "*"