
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-31T00:10:18+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "fc35d94c01cea4e30c13b12795a4bbfa408bb08b",
 "version": "0.3.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
