[tool.poetry]
name = "sys-vars"
version = "4.0.3"
description = "Access system variables in your code as native Python data types."
authors = ["Caleb <le717@users.noreply.github.com>"]
license = "MIT"
readme="README.md"
repository="https://github.com/le717/sys-vars"
include = ["py.typed", "sys_vars.pyi"]
classifiers = [
    "Typing :: Typed"
]

[tool.poetry.dependencies]
python = "^3.7"
python-dotenv = "^0.19.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.9"
python-dotenv = "^0.19.0"
black = "^20.8b1"
mypy = "^0.910"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
