# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ivi_sdk.api.order import definition_pb2 as api_dot_order_dot_definition__pb2


class OrderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateOrder = channel.unary_unary(
                '/ivi.rpc.api.order.OrderService/CreateOrder',
                request_serializer=api_dot_order_dot_definition__pb2.CreateOrderRequest.SerializeToString,
                response_deserializer=api_dot_order_dot_definition__pb2.Order.FromString,
                )
        self.GetOrder = channel.unary_unary(
                '/ivi.rpc.api.order.OrderService/GetOrder',
                request_serializer=api_dot_order_dot_definition__pb2.GetOrderRequest.SerializeToString,
                response_deserializer=api_dot_order_dot_definition__pb2.Order.FromString,
                )
        self.FinalizeOrder = channel.unary_unary(
                '/ivi.rpc.api.order.OrderService/FinalizeOrder',
                request_serializer=api_dot_order_dot_definition__pb2.FinalizeOrderRequest.SerializeToString,
                response_deserializer=api_dot_order_dot_definition__pb2.FinalizeOrderAsyncResponse.FromString,
                )


class OrderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinalizeOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrder,
                    request_deserializer=api_dot_order_dot_definition__pb2.CreateOrderRequest.FromString,
                    response_serializer=api_dot_order_dot_definition__pb2.Order.SerializeToString,
            ),
            'GetOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrder,
                    request_deserializer=api_dot_order_dot_definition__pb2.GetOrderRequest.FromString,
                    response_serializer=api_dot_order_dot_definition__pb2.Order.SerializeToString,
            ),
            'FinalizeOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.FinalizeOrder,
                    request_deserializer=api_dot_order_dot_definition__pb2.FinalizeOrderRequest.FromString,
                    response_serializer=api_dot_order_dot_definition__pb2.FinalizeOrderAsyncResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ivi.rpc.api.order.OrderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OrderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ivi.rpc.api.order.OrderService/CreateOrder',
            api_dot_order_dot_definition__pb2.CreateOrderRequest.SerializeToString,
            api_dot_order_dot_definition__pb2.Order.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ivi.rpc.api.order.OrderService/GetOrder',
            api_dot_order_dot_definition__pb2.GetOrderRequest.SerializeToString,
            api_dot_order_dot_definition__pb2.Order.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FinalizeOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ivi.rpc.api.order.OrderService/FinalizeOrder',
            api_dot_order_dot_definition__pb2.FinalizeOrderRequest.SerializeToString,
            api_dot_order_dot_definition__pb2.FinalizeOrderAsyncResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
