- name: Add {{item['name']}} to ansible
  add_host:
    hostname: "{{item['name']}}"
    ansible_ssh_host: "{{item['node_egress_ip']}}"
    ansible_ssh_user: "{{ssh_user}}"
    ansible_ssh_private_key_filename: "{{ssh_key_filename}}"
    groups: hypervisors

- name: Add {{item['name']}} as an etcd master (if configured)
  add_host:
    hostname: "{{item['name']}}"
    groups: etcd_master
  when: item.get('etcd_master', False)

- name: Add node facts
  set_fact:
    node_name: "{{item['name']}}"
    node_egress_ip: "{{item['node_egress_ip']}}"
    node_egress_nic: "{{item['node_egress_nic']}}"
    node_mesh_ip: "{{item['node_mesh_ip']}}"
    node_mesh_nic: "{{item['node_mesh_nic']}}"
    node_is_etcd_master: "{{item['etcd_master'] | default(False)}}"
  delegate_to: "{{item['name']}}"
  delegate_facts: true
