
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-01T20:22:45+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "1ba8f92f8773141cd31e0163754d86eff29279bc",
 "version": "1.6.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
