[tool.poetry]
name = "nvme"
version = "0.1.0"
description = ""
authors = ["Gregory C. Oakes <gregcoakes@gmail.com>"]
license = "MIT"

[tool.poetry.plugins."nvme.drivers.linux"]
"linux" = "nvme.driver.linuxioctl:LinuxIoctlDriver"

[tool.poetry.dependencies]
python = ">=3.6.0"
importlib-metadata = "^4.8.1"

[tool.poetry.dev-dependencies]
flake8-black = "^0.2.3"
black = {version = "^21.7b0", python = ">=3.6.2"}
flake8-docstrings = "^1.6.0"
pdoc3 = "^0.10.0"
pytest = "^6.2.4"
isort = {version = "^5.9.3", python = ">=3.6.1,<4.0"}
flake9 = "^3.8.3"
flake8-isort = "^4.0.0"

[tool.isort]
profile = "black"

[tool.flake8]
max-line-length = 88
extend-ignore = "E203"

[tool.pytest.ini_options]
markers = ["device"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
