# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/order/definition.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common/order/definition.proto',
  package='ivi.proto.common.order',
  syntax='proto3',
  serialized_options=b'\n)games.mythical.ivi.sdk.proto.common.orderP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1d\x63ommon/order/definition.proto\x12\x16ivi.proto.common.order*w\n\nOrderState\x12\x0b\n\x07STARTED\x10\x00\x12\x0e\n\nPROCESSING\x10\x01\x12\r\n\tASSIGNING\x10\x02\x12\x0c\n\x08\x43OMPLETE\x10\x03\x12\x0c\n\x08\x44\x45\x43LINED\x10\x04\x12\n\n\x06\x46\x41ILED\x10\x05\x12\x08\n\x04PAID\x10\x06\x12\x0b\n\x07\x45XPIRED\x10\x07\x42-\n)games.mythical.ivi.sdk.proto.common.orderP\x01\x62\x06proto3'
)

_ORDERSTATE = _descriptor.EnumDescriptor(
  name='OrderState',
  full_name='ivi.proto.common.order.OrderState',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STARTED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PROCESSING', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ASSIGNING', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COMPLETE', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DECLINED', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PAID', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EXPIRED', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=57,
  serialized_end=176,
)
_sym_db.RegisterEnumDescriptor(_ORDERSTATE)

OrderState = enum_type_wrapper.EnumTypeWrapper(_ORDERSTATE)
STARTED = 0
PROCESSING = 1
ASSIGNING = 2
COMPLETE = 3
DECLINED = 4
FAILED = 5
PAID = 6
EXPIRED = 7


DESCRIPTOR.enum_types_by_name['OrderState'] = _ORDERSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
