[tool.poetry]
name = "quack-cli"
version = "0.2.1"
description = "A CLI for the Quackstack API"
authors = ["Kronifer <44979306+Kronifer@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
typer = {extras = ["all"], version = "^0.4"}
requests = "^2.26.0"

[tool.poetry.scripts]
quack = "quack_cli.main:app"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
