# coding: utf-8

"""
    Quickpac API

    Here you will find all public interfaces to the Quickpac system.  # noqa: E501

    OpenAPI spec version: v1.00

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import quickpac
from quickpac.models.print_addresses_type import PrintAddressesType  # noqa: E501
from quickpac.rest import ApiException


class TestPrintAddressesType(unittest.TestCase):
    """PrintAddressesType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPrintAddressesType(self):
        """Test PrintAddressesType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = quickpac.models.print_addresses_type.PrintAddressesType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
