# coding: utf-8

"""
    Quickpac API

    Here you will find all public interfaces to the Quickpac system.  # noqa: E501

    OpenAPI spec version: v1.00

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import quickpac
from quickpac.api.pickup_migros_api import PickupMigrosApi  # noqa: E501
from quickpac.rest import ApiException


class TestPickupMigrosApi(unittest.TestCase):
    """PickupMigrosApi unit test stubs"""

    def setUp(self):
        self.api = PickupMigrosApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_pickmup_set_paket_status_get(self):
        """Test case for pickmup_set_paket_status_get

        SetPaketStatus  # noqa: E501
        """
        pass

    def test_pickmup_set_paket_status_post(self):
        """Test case for pickmup_set_paket_status_post

        SetPaketStatus  # noqa: E501
        """
        pass

    def test_pickmup_set_ruecksendung_get(self):
        """Test case for pickmup_set_ruecksendung_get

        SetRuecksendung  # noqa: E501
        """
        pass

    def test_pickmup_set_ruecksendung_post(self):
        """Test case for pickmup_set_ruecksendung_post

        SetRuecksendung  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
