# coding: utf-8

"""
    Quickpac API

    Here you will find all public interfaces to the Quickpac system.  # noqa: E501

    OpenAPI spec version: v1.00

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import quickpac
from quickpac.models.mode_type import ModeType  # noqa: E501
from quickpac.rest import ApiException


class TestModeType(unittest.TestCase):
    """ModeType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModeType(self):
        """Test ModeType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = quickpac.models.mode_type.ModeType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
