# coding: utf-8

"""
    Quickpac API

    Here you will find all public interfaces to the Quickpac system.  # noqa: E501

    OpenAPI spec version: v1.00

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import quickpac
from quickpac.models.message_type import MessageType  # noqa: E501
from quickpac.rest import ApiException


class TestMessageType(unittest.TestCase):
    """MessageType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMessageType(self):
        """Test MessageType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = quickpac.models.message_type.MessageType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
