# coding: utf-8

"""
    Typewise API

    Typewise server for text completion, autocorrection and emoji searching.  # noqa: E501

    OpenAPI spec version: 0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import typewiseprediction
from typewiseprediction.models.all_of_last_word_correction_request_sentence_keyboard import AllOfLastWordCorrectionRequestSentenceKeyboard  # noqa: E501
from typewiseprediction.rest import ApiException


class TestAllOfLastWordCorrectionRequestSentenceKeyboard(unittest.TestCase):
    """AllOfLastWordCorrectionRequestSentenceKeyboard unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfLastWordCorrectionRequestSentenceKeyboard(self):
        """Test AllOfLastWordCorrectionRequestSentenceKeyboard"""
        # FIXME: construct object with mandatory attributes with example values
        # model = typewiseprediction.models.all_of_last_word_correction_request_sentence_keyboard.AllOfLastWordCorrectionRequestSentenceKeyboard()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
