[tool.poetry]
name = "describe-json"
version = "0.16"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
pydevd-pycharm = "^212.5284.18"

[tool.poetry.dev-dependencies]
pycallgraph = "^1.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
