# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import jgreenepack
from jgreenepack.models.platform_type import PlatformType  # noqa: E501
from jgreenepack.rest import ApiException


class TestPlatformType(unittest.TestCase):
    """PlatformType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlatformType(self):
        """Test PlatformType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = jgreenepack.models.platform_type.PlatformType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
