
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-06T15:30:27+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "30defb270d2828db4f03e6ae9e2fc01934ce6389",
 "version": "0.7.dev1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
